### ISSUE TITLE
bug(orderedReducer): DOCUMENT_ADDED action not correctly updating state for subcollections

### ISSUE THREAD

**Issue by igor-lemon** [prescottprue/redux-firestore#101]
I think adding document action at `ordered` reducer doesn't work correct.
I added new document into `sources/{userID}/cards` collection but new document at `ordered` reducer was put into `sources` obj, not  `sources/{userID}/cards` 
But new doc was put correct into `data` reducer 
![image](https://user-images.githubusercontent.com/14764799/40261155-bedccb56-5b07-11e8-9b1d-4ae6526fa894.png)

**Comment by prescottprue** [comment]
It looks like the DOCUMENT_ADDED for ordered isn't handling subcollections yet. If you have a listener attached for that path, it should correctly update state.

**Comment by prescottprue** [comment]
@igor-lemon I have been debugging and am seeing some different results (also not correct though). Did you using the `add` method to add the document? or dispatch it yourself?

What action action was dispatched right before? Thanks for reporting - I am finding that if you do not have a listener attached to the specific sub collection things do not work at all as expected.

**Comment by igor-lemon** [comment]
Yep

**Comment by prescottprue** [comment]
Fixed in the [v0.5.4 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.5.4). Reach out if it isn't working as expected. Thanks for reporting!

**Comment by igor-lemon** [comment]
Thanks
