### ISSUE TITLE
bug(orderedReducer): LISTENER_RESPONSE action not correctly updating state for subcollections 

### ISSUE THREAD

**Issue by igor-lemon** [prescottprue/redux-firestore#103]
After doc delete `ordered` object doesn't update, was updated only `data` object.

**Comment by prescottprue** [comment]
@igor-lemon If you use `storeAs` things should work as expected. I am working on some `LISTENER_RESPONSE` changes that are on the [`0.5.5`](https://github.com/prescottprue/redux-firestore/pull/104). Is it possible for your to pull that branch and [follow the link instructions](http://react-redux-firebase.com/docs/contributing.html#npm-linking) to checkout if it fixes things for you?

It seems that tests passed correctly, but when testing it didn't seem like references were being updated correctly.


It also would be helpful if you could provide your connect logic and listener logic (may be in `firestoreConnect`).

**Comment by igor-lemon** [comment]
Sure. 
So, I installed 0.5.5 and don't see any changes. After delete updates only data collection.

No I think it isn't relating with connect method. For reproduce set a listener fo deep collection and after delete a document from this collection. I can show you my code but it code isn't simple and you will not reproduce it fast on your side. Let's try to repeat steps that I wrote above.

**Comment by prescottprue** [comment]
@igor-lemon I understand that it isn't due to the `connect` method - I am trying to replicate your exact use case. To do that it helps if you can provide which listeners you are creating, how and how you are connecting to state.

I have repeated your steps, but without more detail on the setup it is tough to try to repro.

**Comment by igor-lemon** [comment]
@prescottprue Ok. Tomorrow I'll write a small sample for reproduce the bug.

**Comment by prescottprue** [comment]
@igor-lemon Open to a replication if you ever got a chance to make one.

There have been a number of issues reported relating to how subcollections are stored. To address these, I have [started the v1.0.0 Roadmap doc](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) which includes notes about the current plans for the new state pattern.

This new state pattern should make it relatively easy to debug issues like this.

**Comment by prescottprue** [comment]
Fixed in [`v0.7.0` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.7.0). Thanks for reporting.
