### ISSUE TITLE
bug(actions): `firestore.runTransaction` always fails

### ISSUE THREAD

**Issue by ejoubaud** [prescottprue/redux-firestore#108]
Hi @prescottprue 👋 First of all awesome work on those awesome libs, thanks a lot!

**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Any call to `firestore.runTransaction`, at least with the `firestore` prop provided by `withFirestore`, results in a `Cannot read property 'apply' of undefined` error because it ends up calling `.runTransaction` on the `firebase.firestore` creator function instead of the `Firestore` object returned by `firebase.firestore()`.

**What is the expected behavior?**

Start a Firestore transaction.

I believe I've nailed down the culprit LOC at https://github.com/prescottprue/redux-firestore/blame/84c0a6ea764c77c1548b608c4d43979622108ff7/src/actions/firestore.js#L384 It should be `ref: firebase.firestore()` (or maybe `ref: firestoreRef(firebase, dispatch, meta)`, as used in other methods) instead of `ref: firebase.firestore` if this should ever work. Adding a breakpoint in there shows that, at that point of execution, `firebase.firestore` is a function and `firebase.firestore()` returns the `Firestore` obj with the `runTransaction` method.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

Looks like that feature was added in #92, so probably v0.5.1+

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Just provide `firestore` with `withFirestore` and try to call `firestore.runTransaction(anything)` anywhere. See https://codesandbox.io/s/m38yj7248p (you may need to click the reload button in the preview window, the firebase loading is a bit funky)

It might be worth testing the feature further with a transaction with actual content, because I suspect if it fails that early, there may be other failures awaiting inside a transaction.

**Comment by prescottprue** [comment]
Weird, this didn't seem to be an issue in the past, but what you are mentioning looks correct. Open to a PR if you get a chance, otherwise, I will try to get to it soon.

**Comment by prescottprue** [comment]
Fixed in [`v0.5.5.` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.5.5). There are now some basic unit tests as well. Reach out if things aren't working as expected.
