### ISSUE TITLE
Listener drops link to create index

### ISSUE THREAD

**Issue by matt-tingen** [prescottprue/redux-firestore#112]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When a listener fails due to a missing index, an error is added to the store, but the corresponding link provided by the firestore SDK is swallowed.

**What is the expected behavior?**
A direct link to create the necessary index is surfaced either in the error store or in the console.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

`redux-firestore`: `0.5.4`
Chrome v66

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
Setup a listener which requires a compound index, but no index exists. For example (with `react-redux-firebase`:
```
firestoreConnect([{
      collection: 'items',
      orderBy: [['name', 'asc']],
      where: ['userId', '==', 'myUserId'],
}])
```

**Comment by matt-tingen** [comment]
This is just a specific instance, but in general, it seems that a fair amount of info is lost from errors. Another example would be when the query is not allowed by rules. With the firestore SDK, the error is "Error: Missing or insufficient permissions." which indicates the problem. With `redux-firestore`, the error is simply
```
{
  "code": "failed-precondition",
  "name": "FirebaseError"
}
```
which is the same as when an index is missing.

Being fairly new to firebase, it would be very helpful to have these error messages surfaced somewhere.

**Comment by prescottprue** [comment]
@matt-tingen the `logErrors` config option should make it so that these errors are shown within the console.

That said, I like the idea of looking into making the errors that are written to state more clear and preserve more info about the error.

**Comment by CoVoCre** [comment]
@prescottprue where is this `logErrors` config option described ? I only see logListenerError for example...
Also, I wonder where I should actually set config options. Should I add them as other keys when setting listeners/getting data ?
Lastly, how can we unset listeners ? I've simply tried `unsetListener({...})` with `{...}` specifying the same as when I set the listener I want to unset.

**Comment by CoVoCre** [comment]
Well, actually I saw in the [simple example Todos.js](https://github.com/prescottprue/redux-firestore/blob/master/examples/basic/src/Todos.js) that unsetListener seems to be the way to go. I'll add it to the readme if that's ok.
Also, the idea of using a component var listenerSettings for each listener set in order to be able to unset later is pretty good, I'll write it to the readme as a suggestion/example of uses if that's ok !

**Comment by prescottprue** [comment]
@CoVoCre Great input, and thanks for the additions! Have you checked out the `firestoreConnect` HOC offered by `react-redux-firebase`? It automatically handles attaching/detaching listeners on component mount/unmount.

**Comment by CoVoCre** [comment]
@prescottprue yes I did, but I think it's a lot of overhead for what I need which isn't very intense, for now 😉

**Comment by prescottprue** [comment]
@matt-tingen were you able to update and use `logErrors` as expected? Closing for now since this functionality is on the `next` tag.
