### ISSUE TITLE
unexpect delete behavior

### ISSUE THREAD

**Issue by Louis-Tian** [prescottprue/redux-firestore#113]
**Do you want to request a *feature* or report a *bug*?**  
Report a bug

**What is the current behavior?**
`props.firestore.delete` removes the doc's field by setting the doc to `null`
![image](https://user-images.githubusercontent.com/5655024/41468589-de12b30e-70ed-11e8-950b-5a2821d10cc1.png)

**What is the expected behavior?**
`props.firestore.delete` should be completely removed, including the document id. 

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
redux-firestore@0.5.4

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by Louis-Tian** [comment]
Hi @prescottprue, 0.5.4 is the version I am using. I just test it with 0.5.7, seeing the same behavior.

Is this behavior is designed intentionally for some reason? The test code is suggestion it is but I don't understand why. 

https://github.com/prescottprue/redux-firestore/blob/a7c7caa91997fb1469f6d267743b8a6d67d1db41/test/unit/reducers/dataReducer.spec.js#L256-L263

I thought the test case would be somtething like: 
```javascript
expect( 
  dataReducer({ [collection]: { [doc]: { thing: 'asdf' } } }, action), 
)[collection].to.not.have.key(doc);
```

**Comment by Louis-Tian** [comment]
https://github.com/prescottprue/redux-firestore/blob/a7c7caa91997fb1469f6d267743b8a6d67d1db41/src/reducers/dataReducer.js#L72-L83

probably should be changed to 
```
 case DOCUMENT_REMOVED: 
 case DELETE_SUCCESS: 
   const removePath = pathFromMeta(action.meta); 
   if (action.preserve && action.preserve.data) { 
     return preserveValuesFromState( 
       state, 
       action.preserve.data, 
       setWith(Object, removePath, null, state), 
     ); 
   } 
   return unset(state, removePath); 
```

**Comment by prescottprue** [comment]
@Louis-Tian Setting the value to `null` is how it is indicated that data has been loaded, but does not exist. That is different than `undefined` which indicates that it is not yet loaded. `unset` will cause the value to be `undefined`.

Totally open to placing this behind a configuration option as long as it is documented. Feel free to open a pull request if you have the time.

**Comment by munroAllie** [comment]
@prescottprue @Louis-Tian 
Is there any work around available for this? My components .map functions break upon deleting an item because state says the an item in the array is now null appose to removing it. Only when I refresh the page does the store work as expected.

**Comment by demoran23** [comment]
@munroAllie You can work around that by adding the following predicate prior to your maps:

`.filter(el => el)`

**Comment by prescottprue** [comment]
Closing since setting to `null` is intentional. For those looking to not have null in a list of data, using `ordered` is suggested. If you do want to use `data`, logic can be used to remove falsey values from a list as shown above by @demoran23: `.filter(el => el)`

**Comment by gregfenton** [comment]
Is this documented in the redux-firestore README or elsewhere?  I spent several hours dealing with this issue on a react-native project...layers upon layers... ☹️

Are we saying that essentially: `ordered` contains valid entries and `data` _might_ contains some values that are `null` ?  And that it is valid/okay/best_practice(?) to filter out entries from `data` that are null using `.filter(el => el)` ?

In my case, I have 2 lists on the screen at once ("open" and "done"), each with their own listener. As I click a button to toggle `done: !todo.done`, I often end up with entries in both `state.firestore.data.open` and `state.firestore.data.done` where one collection has the document data and the other collection has `null`.

**Comment by prescottprue** [comment]
@gregfenton The plan is to move to just storing keys in the `ordered` section of state to help prevent confusion between the two

In the meantime, if you think there is anything we could add to the README to make it more clear, open to PRs

**Comment by gregfenton** [comment]
I'll gladly toss in a PR, just want to be sure I know what it should state 😄 

Maybe just a "NOTE" that indicates that "best practice is to use `.ordered`" and that `.data` is likely to be deprecated in future releases.

Is that accurate enough?

**Comment by prescottprue** [comment]
No, data isn't really going away it is actually where data will live and ordered will be keys, I think it is more like

"Best practice is to use `.ordered` for keys/order only, and use `.data` for actual object data" - this actually mirrors [best practices listed in the redux docs](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#relationships-and-tables)
