### ISSUE TITLE
bug(reducers): ordered state not updated with added item in array

### ISSUE THREAD

**Issue by michaelspeed** [prescottprue/redux-firestore#116]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
If i add a document to firestore, the state at 
`
    state.firestore.ordered['someList]
`
will not update correctly, all the existing items will still be in the array, with repeated items along with the new item, when i update an item the item still remains in the state, and the updated item will add itself to the array. this leads to repeations
**What is the expected behavior?**
Expected is to delete the whole array from the state, and then create new item with the existing item.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
react-redux-firebase: 2.1.6
redux-firestore: 0.5.7

**Comment by prescottprue** [comment]
There have been a number of issues reported relating to how subcollections are stored. To address these, I have [started the v1.0.0 Roadmap doc](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) which includes notes about the current plans for the new state pattern.

This new state pattern should make it relatively easy to debug issues like this.

**Comment by prescottprue** [comment]
Just to clarify:

Are you adding the document directly to state or calling a method to write to Firestore? Writes directly to state WILL NOT update Firestore or RTDB, it requires calling a method which in turn dispatches an action.

**Comment by michaelspeed** [comment]
i think this is fixed
