### ISSUE TITLE
Add new document to a subcollection

### ISSUE THREAD

**Issue by Lando-L** [prescottprue/redux-firestore#117]
**Do you want to request a *feature* or report a *bug*?**  
I want to report a bug

**What is the current behavior?**
I cannot (or at least it is not obvious to me how to) add a document to a subcollection. I tried something like
```
firestore.update({
    collection: "...",
    doc: "...",
    subcollection: [{ collection: "...", doc: "newId" }]
}, { newDoc: {} })

firestore.add({
    collection: "...",
    doc: "...",
    subcollection: [{ collection: "..." }] }
, { newDoc: {} })
```
but `update` doesn't add something if the subcollection does not exist already and `add` runs into the error `TypeError: Cannot read property 'apply' of undefined`

**What is the expected behavior?**
Be able to add a new document to an existing subcollection or create the subcollection if it doesn't exist already.

**Comment by prescottprue** [comment]
@Lando-L I may be misunderstanding, but I believe you are pointing to the wrong path. As mentioned in the docs, the parameter to pass to the query config is [`subcollections`](https://github.com/prescottprue/redux-firestore#sub-collections).

**Comment by TITAN9389** [comment]
i got the same error but i'm using `subcollections` TypeError: Cannot read property 'apply' of undefined.

**Comment by prescottprue** [comment]
@TITAN9389 Please open an issue that includes code, steps to replicate, and the versions of dependencies you are using so an error can be replicated.
