### ISSUE TITLE
Querying for a single doc in a collection fails from unexpected return type

### ISSUE THREAD

**Issue by diagramatics** [prescottprue/redux-firestore#12]
Traced the codebase and it seems to have originated from somewhere around `setListener` at https://github.com/prescottprue/redux-firestore/blob/master/src/actions/firestore.js#L173.

Say I'm querying for a doc `bar` inside the `foo` collection. The snapshot returned by the Firestore reference would be a `DocumentSnapshot` instead of `QuerySnapshot`, meaning it would not have a `.forEach()` and would return `null` in `dataByIdSnapshot` or `orderedFromSnap`

Not sure if I'm missing something here. Instead of using `firebase` I used `@firebase/app` and `@firebase/firestore` for their separate ES bundles and also `react-redux-firebase`. Docs in Firestore have pointed to expecting a `DocumentSnapshot` instead of `QuerySnapshot` though.

**Comment by prescottprue** [comment]
Looking into this now. Thanks for reporting.

**Comment by prescottprue** [comment]
I was able to confirm. Working on a fix now.

**Comment by prescottprue** [comment]
[v0.1.0-alpha.2](https://github.com/prescottprue/redux-firestore/releases/tag/v0.1.0-alpha.2) includes a fix for this.

So far it was tested with `get` by passing with a slash like so:
```js
get('todos/123Some') // where 123Some is a todo document id
```

**Comment by diagramatics** [comment]
That was fast, thanks!
