### ISSUE TITLE
Adding a subcollection

### ISSUE THREAD

**Issue by tebogos** [prescottprue/redux-firestore#120]
**Do you want to request a *feature* or report a *bug*?**  
bug

Is it posible to add a subcollection to firestore using redux-firestore?
**What is the current behavior?**
when I add a sub document I like the code below:

withHandlers({
    startNewProcess: props => () =>
      props.firestore.add(`Region/${region}/office/${id}`, { name:props.name})
})
I have also tried  props.firestore.add({collection:"Region",doc:region,subcollections[collection:"office"],doc:id}, { name:props.name})
I get the error below:

 Cannot read property 'apply' of undefined
    at wrapInDispatch (actions.js:57)
    at Object.add (firestore.js:52)
    at Object.add (actions.js:92)
    at NewProcessForm.jsx:140
    at Recompose.esm.js:183
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:483)
    at executeDispatchesAndRelease (react-dom.development.js:581)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:592)
    at forEachAccumulated (react-dom.development.js:562)
    at runEventsInBatch (react-dom.development.js:723)
    at runExtractedEventsInBatch (react-dom.development.js:732)
    at handleTopLevel (react-dom.development.js:4476)
    at batchedUpdates$1 (react-dom.development.js:16659)
    at batchedUpdates (react-dom.development.js:2131)
    at dispatchEvent (react-dom.development.js:4555)
    at interactiveUpdates$1 (react-dom.development.js:16714)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4532)
wrapInDispatch @ actions.js:57
add @ firestore.js:52
(anonymous) @ actions.js:92
(anonymous) @ NewProcessForm.jsx:140
(anonymous) @ Recompose.esm.js:183
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4476
batchedUpdates$1 @ react-dom.development.js:16659
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4555
interactiveUpdates$1 @ react-dom.development.js:16714
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532

**What is the expected behavior?**
I expect that the data will stored in firestore under the subcollection in the case "office" with the id provided.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
I am using version 2.

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by prescottprue** [comment]
It is difficult to tell from the syntax highlighting what you are mentioning you have tried. 

```
```

**Comment by tebogos** [comment]
Thanks for the prompt response.
What is the correct way to add data to subcollection in firestore using redux-firesore?

**Comment by tebogos** [comment]
I am trying to update my firestore database with the data from the from a form.
I am using reactjs client.
Please see the code example below:
`
const enhance = compose(
  withFirestore, // firestoreConnect() can also be used
  withStateHandlers(
    ({ initialVal = '' }) => ({
      region: initialVal,
      zone:initialVal,
      processDefinitionId:initialVal,
      processName:initialVal,
      firmName:initialVal,
      firmNumber:initialVal,
      requestorName:initialVal,
      requestorContact:initialVal,
      workType:initialVal,
      requetorId:initialVal,
      assignee:initialVal,
      seniorAgent:initialVal,
      date:new Date(),
      businessKey:initialVal

    }),
    {
      onWorkTypeChange: ({ workType }) => (e) => ({ workType: e.target.value }),
      onRegionChange: ({ region }) => (e) => ({ region: e.target.value }),
      onZoneChange: ({ zone,businessKey }) => (e) => ({ zone:e.target.value,businessKey:e.target.value+"-"+moment().format('YY')+"-"+moment().month()+"-"+
       moment().day()+"-"+moment().hour()+"-"+moment().minute()+"-"+moment().second() }),
      // onprocessDefinitionIdChange: ({ processDefinitionId }) => (e) => ({ processDefinitionId:e.target.value }),
      onProcessNameChange: ({ processDefinitionId,processName }) => (e) => ({ processDefinitionId:e.target.value,processName:getNameById(processList,e.target.value )}),
      onFirmNameChange: ({ firmNumber,firmName }) => (e) => ({ firmName:e.target.value ,firmNumber:e.target.value}),
      // onfirmNumberChange: ({ firmNumber }) => (e) => ({ firmNumber:e.target.value }),
      onRequestorNameChange: ({ requestorName }) => (e) => ({ requestorName:e.target.value }),
      onRequestorContactChange: ({ requestorContact }) => (e) => ({ requestorContact:e.target.value }),
      onRequetorIdChange: ({ requetorId }) => (e) => ({ requetorId:e.target.value }),
      onAssigneeChange: ({ assignee,seniorAgent}) => (e) => ({ assignee:e.target.value,seniorAgent:getReporToById(userList,e.target.value) })
    
    }
  ),
  withHandlers({
    startNewProcess: props => () =>
      props.firestore.add(`Region/${props.region}/processInstance/${props.businessKey}`, { requestorName: props.requestorName, 
        requestorContact: props.requestorContact,firmName:props.firmName,
        firmNumber:props.firmNumber,workType:props.workType,zone:props.zone,date:props.date,
        processDefinitionId:props.processDefinitionId,processName:props.processName,
      region:props.region,assignee:props.assignee,seniorAgent:props.seniorAgent,businessKey:props.businessKey })
  })
)
`

**Comment by tebogos** [comment]
> It is difficult to tell from the syntax highlighting what you are mentioning you have tried.



Sorry it is my fire time posting. Can you see the code below?

`
withHandlers({
    startNewProcess: props => () =>
      props.firestore.add(Region/${props.region}/processInstance/${props.businessKey}, { requestorName: props.requestorName, 
        requestorContact: props.requestorContact,firmName:props.firmName,
        firmNumber:props.firmNumber,workType:props.workType,zone:props.zone,date:props.date,
        processDefinitionId:props.processDefinitionId,processName:props.processName,
      region:props.region,assignee:props.assignee,seniorAgent:props.seniorAgent,businessKey:props.businessKey })
  })
`

**Comment by tebogos** [comment]
> It is difficult to tell from the syntax highlighting what you are mentioning you have tried, but adding a document to a subcollection has been supported for some time.

> Below is a copy and paste from your example:


Thank you. It works. But how do I specify  my own subcollection document ID ? 
to get a path like this:   "Regions/someRegion/office/${id}"
Will it be correct to do this?
`
props.firestore.add({
  collection:"Region",
  doc: "someRegion",
  subcollections: [{ collection:"office",doc:${id} }]
}, { name:props.name })`

Thank you for the responce

**Comment by tebogos** [comment]
>When specifiying your own document id at the subcollection level, you can no longer call add since that is for adding documents. If you are trying to update a document at that level you will want to call update like so:

Thank you. You mean that there is no way of specify my own custom document id on a subcollection level?

**Comment by tebogos** [comment]
> Just as a side note: If you have multiple lines of code you want to paste into a comment, if you put "```" on the line before and the line after your code, the syntax formatting will remain. The markdown-cheatsheet explains more, and there are plenty of other markdown syntax resources out there :)

Thank you for the tip!

**Comment by tebogos** [comment]
> When specifiying your own document id at the subcollection level, you can no longer call add since that is for adding documents. If you are trying to update a document at that level you will want to call update like so:

I got it working by using set like so:

``
const docRefConfig = {
   collection:"Region",
  doc: "someRegion",
  subcollections: [{ collection:"office", doc: `${id}` }]
}
props.firestore.set(docRefConfig, { name:props.name })
``
Thank you very much for you prompt  help and tips! 
Regards,
Tebogo.
