### ISSUE TITLE
OrderByChild is not working correctly

### ISSUE THREAD

**Issue by karltaylor** [prescottprue/redux-firestore#131]
I seem to have a problem with OrderByChild not ordering correctly.

Here is my query in `firestoreConnect()`

```js
const userCoupons = {
  collection: 'userCoupons',
  where: [
    ['userId', '==', props.authId],
    ['isRedeemed', '==', false]
  ],
  orderByChild: ['timeCredited', 'desc']
}
```

my Items have a `timeCredit` field which is unix number, but I set them to 1, 2, 3 and 4 for this example, and my ordered data comes back like this:

```
{
  userCoupons: [
    {
      id: 'QTzqk8cLye9sKIT2bcZT',
      isRedeemed: false,
      redeemedAt: null,
      timeCredited: 1,
    },
    {
      id: 'WQaeSPcD2j2rYo6DRT2k',
      isRedeemed: false,
      redeemedAt: null,
      timeCredited: 3,
    },
    {
      id: 'eKspR6fteOGIESawZmpP',
      isRedeemed: false,
      redeemedAt: null,
      timeCredited: 2,
    },
    {
      id: 'nGigV94nUoWCdZYSyLvp',
      isRedeemed: false,
      redeemedAt: null,
      timeCredited: 4,
    }
  ]
}
```

**Comment by karltaylor** [comment]
The only way I've got round this at the moment is to hack a sort function in my connect.

```
const sortTheArray = state.firestore.ordered.userCoupons.sort(function (a, b) {
      return a.timeCredited - b.timeCredited
    })
```

Then I actually get properly a properly sorted array 🤔

**Comment by prescottprue** [comment]
@karltaylor Firestore uses [`orderBy`](https://github.com/prescottprue/redux-firestore#orderby) not `orderByChild` (what RTDB uses).

You are not the first to have this happen though, so maybe we should add a warning for any query params that do not match [the specified query options in the docs](https://github.com/prescottprue/redux-firestore#query-options). 

Let me know if things still don't work as you expect once you switch it to `orderBy`.

**Comment by karltaylor** [comment]
When I use `orderBy` the data is not available / does not appear in `firestore.data` or `firestore.ordered`?

**Comment by prescottprue** [comment]
@karltaylor You may be getting a query error due to not having the indexes setup within Firestore. 

The errors are set to the errors state, or you should see the errors in the console with `logErrors: true`.
