### ISSUE TITLE
bug(reducers): updates to arrays inside documents don't work as expected

### ISSUE THREAD

**Issue by pdyxs** [prescottprue/redux-firestore#140]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
If you store an array inside a firestore document (e.g. `{ content: ['an', 'array'] }`) and update that document such that the array is shorter (`{ content: ['single'] }`), the update action that fires merges the arrays and doesn't delete the extra elements (`{ content: ['single', 'array'] }`).

Note that `{ content: ['single'] }` is what is in the firestore database at this stage.

**What is the expected behavior?**
For the array to be pruned

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
Definitely exists in 0.5.8, unclear if it worked previously

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
See pull request and the test attached.

**Comment by GuillemotF** [comment]
I have a similar behaviour with objects in a document (instead of an array) when removing a property.

Example : 

```
firestore.update(
      {
        collection: 'test',
        doc: 'someId',
      },
      {
        someObject.someProperty: firestore.FieldValue.delete();
      },
);
```

Will correctly updates `data` state in redux but not the `ordered ` one.

**Comment by prescottprue** [comment]
@GuillemotF The current issue with this fix has to due with how subcollections will no longer merge onto document objects. I'm currently working on a new pattern for redux state where subcollections will not be stored on the doc directly.

That said, I'm open to merging this change to a `next` release, we will just need to make sure we note that it will be breaking for some.

**Comment by prescottprue** [comment]
[Started the v1.0.0 Roadmap doc](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) which includes notes about the current plans for the new state pattern.

It seems like we might be able to release this under a flag before 1.0.0 so that folks can use it in the meantime.

**Comment by GuillemotF** [comment]
@prescottprue Thanks for these explanations, I think that separating the sub-collections from the documents is the only "Firestore's way" to do since it is also possible to have a property of a document of the same name as a sub-collection.

Maybe you can have a compromise like this : 

```
// Data
{
  projects: {
    myProject: {
      subCollections: {
        events: {
          ABC123: {
          
          }
        }
      }
    }
  }
}
// Ordered
{
  projects: [
    {
      id: 'myProject'
      subCollections : {
        events: [
          {
            id: 'ABC123'
          }
       }
      ]
    }
  ]
}
```
But it may be hard to make this working properly.

**Comment by prescottprue** [comment]
@GuillemotF The structure proposed in the Roadmap stores the subcollections by the parent document key still, it is just not under the same doc object within redux:

```js
```

**Comment by compojoom** [comment]
That looks like a good change. Another side-effect of the current way we store the subcollection is that whenever you try to update the parent document and you read the document from redux - you also get the subcollection as property on the doc... And if you try to store the parent document - you also store the subcollection as prop on the document, which is often not desired.

**Comment by prescottprue** [comment]
@compojoom Exactly! Definitely another reason behind the change. Glad to have others looking into it since it is such a large change.

Since getting from state with the new syntax could possibly be confusing, I included some [state selection utilities](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap#state-selection-utilities) called `firestoreDataSelector` and `firestoreOrderedSelector`.

Interested to hear input on how using the new syntax feels, so if anyone gets a chance to check it out, post your thoughts. Totally open to renaming things, adding more utilities, or changing their syntax - the goal is to make it as easy to use as possible.

**Comment by prescottprue** [comment]
[`v0.7.0` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.7.0) includes a fix for updating array items. Thanks to all for reporting!

**Comment by YuvalKlein** [comment]
Yeesss!! working!
thank you!

**Comment by prescottprue** [comment]
Reopening since it was mentioned here: https://github.com/prescottprue/react-redux-firebase/issues/719

**Comment by loginov-rocks** [comment]
Unfortunately, able to reproduce intermittently with v0.8.0. Does it makes sense to manually bind to `data` object instead of `ordered` or the latter has been planned to be stable feature? Thanks!

**Comment by djpeach** [comment]
I think I am having the same issue. I am listening to a document with 

```
firestoreConnect(props => [
    {collection: <my-collection>, doc: <my-doc-id>},
  ]),
```

And it works perfectly and updates the react component if I add a field to the doc, or update an existing field. However, if a delete a field from that doc... crickets. Nothing happens and I have to reload the component manually to see the change reflected on the app.

**Comment by prescottprue** [comment]
Seems like this logic is also causing other issues such as #243. I'm working on changing the merging logic back - as part of that there will be an error log if there is a query with `subcollections` that is not using `storeAs`. I think this will also help prepare folks for the [upcoming v1 changes which store all subcollections at the top level](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap).

Thanks to all for reporting

**Comment by prescottprue** [comment]
This should now be working as expected with [the v0.10.0 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.10.0).  

If things aren't working perfectly please feel free to open a new issue with a reproduction case, Thanks to all for reporting!
