### ISSUE TITLE
Do not add nonserializable objects in the redux store

### ISSUE THREAD

**Issue by dimitropoulos** [prescottprue/redux-firestore#145]
## Bug: should not store functions in the redux state tree
for example
```store.firestore.add({ collection: 'cities' }, { name: 'Some Place' }),```
is storing the `add` function in the state tree.

[The Redux docs](https://redux.js.org/faq/organizingstate#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) say it best:

> It is highly recommended that you only put plain serializable objects, arrays, and primitives into your store. It's technically possible to insert non-serializable items into the store, but doing so can break the ability to persist and rehydrate the contents of a store, as well as interfere with time-travel debugging.
> 
> If you are okay with things like persistence and time-travel debugging potentially not working as intended, then you are totally welcome to put non-serializable items into your Redux store. Ultimately, it's your application, and how you implement it is up to you. As with many other things about Redux, just be sure you understand what tradeoffs are involved.

I'd like to better understand your design choice here to break such a commonly held standard.  I'm assuming there's just something I don't understand.

**What is the current behavior?**
functions in the redux state tree

**What is the expected behavior?**
no functions in the redux state tree

**Comment by prescottprue** [comment]
@dimitropoulos This is not part of the state tree and is not "in the store". It is attached "on" the store as an enhancer. To view what is in state, *which is a plain object*, use `store.getState()`.

**Comment by prescottprue** [comment]
@dimitropoulos Does my comment address your question in a way that things are now clear? Going to close, but please feel free to reach out if you have any more questions.
