### ISSUE TITLE
question: take result of first read and use it to fetch additional data

### ISSUE THREAD

**Issue by iFallUpHill** [prescottprue/redux-firestore#148]
```js
import React from 'react';
import { compose } from 'redux';
import { connect } from 'react-redux';
import { firestoreConnect } from 'react-redux-firebase';

{ ... }

const mapStateToProps = state => {
    return {
        transactions: state.firestore.ordered.transactions,
    }
}

export default compose(
    connect(mapStateToProps),
    firestoreConnect([
        { collection: 'transactions', limit: 10, orderBy: ['createdAt', 'desc']}
    ]),
)(Listing);
```

**What is the current behavior?**
I store `uid`s of users inside of each transaction document with the intention of building a nested document for each transaction containing the transaction information and user information in one object per transaction. Is this possible and if so what approach would you recommend? Usually, when using sagas I would just resolve the document first then make a second read for the particular user document. Unsure how to do this with `firestoreConnect` though.

**What is the expected behavior?**
1. Get 10 most recent transactions
2. Each transaction contains a uid to a user in the /users/ collection
3. For each transaction, take that uid and merge the relevant user document into the transaction object

**Comment by prescottprue** [comment]
Population support was released as part of [v0.6.0-alpha.3](https://github.com/prescottprue/redux-firestore/releases/tag/v0.6.0-alpha.3) (make sure to install from the `next` tag, not `latest`)

Here are the docs: https://github.com/prescottprue/redux-firestore/tree/next#population. It is basically a direct port over from `react-redux-firebase`, so [the populate docs for that may be helpful](http://react-redux-firebase.com/docs/populate.html)

Seems like you are looking for something like:

```js
import { firestoreConnect, populate } from 'react-redux-firebase'

const populates = [{ child: 'uid', root: 'users' }] // uid parameter from /users collection
const collection = 'transactions'

export default compose(
    firestoreConnect([
        { collection, limit: 10, orderBy: ['createdAt', 'desc'], populates }
    ]),
    connect((state) => ({
      transactions: populate(state.firestore, collection, populates)
    })),
)(Listing);
```

Let me know if it doesn't work as expected and we can reopen

**Comment by iFallUpHill** [comment]
@prescottprue Works perfectly for me :)

**Comment by iFallUpHill** [comment]
@prescottprue actually, was playing with it a bit more, it looks like if new data is added, it gets pushed to the end of the data in the store from the initial connection and doesn't respect the orderBy? E.g. I have Transaction 4 (T4), T3, T2, and T1. Then, I make a new transaction, T5. The new order, without refreshing is T4, T3, T2, T1, T5.

**Comment by prescottprue** [comment]
@iFallUpHill Is this happening for a subcollection document? If so, try giving `storeAs` a try on your subcollection query.

Either way, I am currently investigating #121, so I'll post updates there.

**Comment by iFallUpHill** [comment]
@prescottprue It's actually just the code snippet you provided, so I don't think this is a subcollection in this case. 

The original transactions collection, with the addition of the nested user document (using `populates` from the `next` branch), results in the order that I described (i.e. new transactions are pushed to the end/bottom instead of merging in the correct order).
