### ISSUE TITLE
[alpha]Adding new document breaks ordered structure

### ISSUE THREAD

**Issue by apietrzak** [prescottprue/redux-firestore#151]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
When listener with `where` query receives new element then ordered object contains weird structure. Instead of 
ordered.addons = [
  {id: 'oldID1', ...restData},
  {id: 'oldID2', ...restData},
  {id: 'newID', ...restData}
]

it looks like:

ordered.addons = [
  {id: 'oldID1', ...restData},
  {id: 'oldID2', ...restData},
  {addons: [
     {new_element}
  ]}
]

**What is the expected behavior?**
After received new document, structure should be still the same:
ordered.addons = [
  {id: 'oldID1', ...restData},
  {id: 'oldID2', ...restData},
  {id: 'newID', ...restData}
]

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
1.0 Alpha

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Query:
{
            collection: 'collections',
            storeAs: 'collection',
            where: ['anotherCollection', '==', firestore.doc(`anotherCollection/${props.anotherCollectionID}`)]
}

**Comment by prescottprue** [comment]
Thanks for reporting, I'll look into this.

**Comment by prescottprue** [comment]
Fixed as part of [v1.0.0-alpha.2 release](https://github.com/prescottprue/redux-firestore/releases/tag/v1.0.0-alpha.2). I also looked into why the tests didn't catch it, and I realized it was because they weren't running on the alpha branch - that is also captured in the release.

Thanks for reporting! Let me know if isn't working as you expect.
