### ISSUE TITLE
Feature Request: StoreAs

### ISSUE THREAD

**Issue by scottfr** [prescottprue/redux-firestore#16]
The 'storeAs' property does not appear to be implement in redux-firestore. It would be very helpful if was supported.

**Comment by prescottprue** [comment]
@scottfr Great to know that there is already interest in this feature. There may be [chat on gitter](https://gitter.im/redux-firestore/Lobby) about it, but major discussion updates will make it back to this thread.

**Comment by benstokoe** [comment]
Yes please! Really need this

**Comment by 0x80** [comment]
I am missing this feature too.

**Comment by prescottprue** [comment]
[The v0.1.0 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.1.0) includes `storeAs`. It should work for both `data` and `ordered` states.

Let me know if it doesn't work as expected. Thanks everyone for reporting and thumbs upping features you hope to see (helps prioritize).

**Comment by 0x80** [comment]
@prescottprue awesome! I'll give it a go soon.
