### ISSUE TITLE
bug(orderedReducer): deleting a sub-collection causes a TypeError

### ISSUE THREAD

**Issue by Wgil** [prescottprue/redux-firestore#161]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When I try to delete a doc in a sub-collection using object or string notation, I get a `TypeError: Cannot read property 'map' of undefined`. Although the sub-collection is deleted, my program stops.

```js
props.firestore
        .delete({
          collection: 'teams',
          doc: 'nOAjBoHrtCY7xH0hi0Io',
          subcollections: [
            {
              collection: 'test',
              doc: 'VUnVU8MDp0uBYo9KAfnW'
            }
          ]
        })
// OR
props.firestore.delete('teams/nOAjBoHrtCY7xH0hi0Io/test/VUnVU8MDp0uBYo9KAfnW')
```

```
TypeError: Cannot read property 'map' of undefined
    at updateItemInArray (reducers.js:98)
    at Object.removeDoc (orderedReducer.js:100)
    at reducer (reducers.js:123)
    at Object.orderedReducer [as ordered] (orderedReducer.js:196)
    at reducers.js:54
    at Array.reduce (<anonymous>)
    at reducers.js:53
    at index.js:26
    at Array.reduce (<anonymous>)
    at push../node_modules/reduce-reducers/es/index.js.__webpack_exports__.default (index.js:25)
    at combination (redux.js:446)
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.dispatch (redux.js:205)
    at e (<anonymous>:1:40553)
    at actions.js:69
```

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
```
"react-redux-firebase": "^2.2.6",
"redux-firestore": "^0.6.1"
```

**Demo**:
https://codesandbox.io/s/8k8l7no240

**Comment by prescottprue** [comment]
Thanks for reporting! Wondering if this would happen with the `next` versions as well since subcollections are stored at the same level as top level collections.

**Comment by Wgil** [comment]
It also happened to me using
```
"react-redux-firebase": "^2.1.9",
"redux-firestore": "^0.6.0"
```
So I updated to see if this had been already solved.

Do you know any workaround while this gets fixed? Although I don't know the codebase I can help to fix it if you address me.

**Comment by prescottprue** [comment]
@Wgil Sorry, I meant the `@alpha` tag which points to to the `1.*.*` version - the upgrade requires a code change since things are stored differently.

**Comment by Wgil** [comment]
Can this happen even if I'm not storing any collection or sub-collection in state?

**Comment by Wgil** [comment]
I just downgraded to `0.5.8` and I'm getting the same error.

**Comment by prescottprue** [comment]
If I am understanding the issue correctly it shouldn't be able to happen unless it is a subcollection. You should be able to get around it using `storeAs` since it seems to be because of the deep nesting.

**Comment by Wgil** [comment]
@prescottprue You're right. I solved it using `storeAs` as you pointed out. From the docs it's not clear to me for what `storeAs` is used for. Why `storeAs` should be used to perform a `delete`? The name makes me thing that it should only be used when storing things.

I was trying to create a CodeSandbox to reproduce the issue but my internet is not going well. I'll create it tomorrow

**Comment by prescottprue** [comment]
@Wgil It is a bug that is because it is deeply nested. `storeAs` makes it so that you can store things as something else within redux. By doing that, then the data isn't nested, but instead stored under the key you provide. When updating, it isn't a nested state update, it is on the top level.

This is actually how v1 works by default, and there are also state selection helpers. That said, I am planning on releasing something that fixes the `0.*.*` series for this issue.

**Comment by Wgil** [comment]
@prescottprue Just updated the description with the link to the demo. Is there any way I can contribute with the library?

**Comment by prescottprue** [comment]
@Wgil Always open to help and PRs! The [alpha branch](https://github.com/prescottprue/redux-firestore/tree/alpha) contains the current progress on the work outlined [in the v1.0.0 Roadmap](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap).

So for help, things I could use:
* Testing of v1 (install through `npm i --save redux-firestore@next`)
* Input about the new API. How does it feel? Do you have any input on changes, even drastic ones, to make things easier/cleaner?
* Help improving the docs of react-redux-firebase and redux-firestore
* Help making it more clear what needs to be done and how folks should help
