### ISSUE TITLE
createFirestoreInstance is not declared in index.d.ts file

### ISSUE THREAD

**Issue by idanlo** [prescottprue/redux-firestore#168]
as said in title, `createFirestoreInstance` is not decalred in the index.d.ts file which means typescript users cannot import it, I can edit the index.d.ts file inside `node_modules` but this is not a fix.

**Comment by prescottprue** [comment]
Fixed in v0.6.3 release

**Comment by mindtricksdev** [comment]
I think this commit broke the import:

![image](https://user-images.githubusercontent.com/5068284/51189889-b08d2f00-18e9-11e9-97a2-538ae7577e54.png)

Note that there's no `func` type in typescript. Maybe you can use `Dispatch` interface from redux for that parameter or just a plain `(action: {}) => any`.

**Comment by prescottprue** [comment]
Whoops, i'll fix that thanks. For some reason ts didn't point that out to me.
