### ISSUE TITLE
getPopulateChild works in a way that we lose the doc ID

### ISSUE THREAD

**Issue by nemo** [prescottprue/redux-firestore#169]
**Do you want to request a *feature* or report a *bug*?**  Bug

**What is the current behavior?**

When populating child documents, the populated results don't include the ID of the document (and there's no way to actually get the ID of the document)

**What is the expected behavior?**

Either return them as DocumentReferences or merge in the document id.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

0.6.2

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Any population of a child array.

**Comment by prescottprue** [comment]
@nemo Thanks for reporting, this is definitely a high priority issue. It seems like returning both the reference and the id might be a good way to go. We could then maybe add an option to not include the doc references for those that are picky about keeping only normal objects/values in state.

**Comment by nemo** [comment]
@prescottprue the PR I sent should solve the problem :)

**Comment by prescottprue** [comment]
Released in v0.6.3, thanks for making a PR!

**Comment by nemo** [comment]
@prescottprue – Thanks for getting this out quickly – already downloaded 0.6.3 and using it!
