### ISSUE TITLE
bug(core): FieldValue missing from firestore instance 

### ISSUE THREAD

**Issue by mindtricksdev** [prescottprue/redux-firestore#172]
In the past versions I could get to `FieldValue` by using the `firestore` instance passed as prop. 

However, after updating to:
"react-redux": "^6.0.0",
"react-redux-firebase": "^3.0.0-alpha.6",
"redux-firestore": "^0.6.3",

I can no longer access that. As a workaround I used the global firestore by importing `firebase` and doing `firebase.firestore.FieldValue` to get the statics I need.

**Comment by prescottprue** [comment]
I think that it may be more clear and help shrink since to have that be the convention moving forward. The `firestore` instance was really meant to have methods that call action dispatchers, and those statics were later added for convince.

Thanks for reaching out.

**Comment by prescottprue** [comment]
Which previous version were you using? Did you happen to change your Firebase JS SDK version as well? Which version of that are you using?

**Comment by mindtricksdev** [comment]
Sorry for the delay. 

`
-    "react-redux": "^5.1.1",
-    "react-redux-firebase": "^2.2.6",
-    "redux-firestore": "^0.5.8",
-    "firebase": "^5.5.8",
+    "redux-firestore": "^0.6.3",
+    "react-redux": "^6.0.0",
+    "react-redux-firebase": "^3.0.0-alpha.6",
+    "firebase": "^5.7.3",
`

**Comment by electricBonfire** [comment]
Just ran into this issue myself

I am using react-native-firebase and had to add 

`import RNFirebase from 'react-native-firebase'`

and then I could call

`RNFirebase.firestore.FieldValue.increment(1)`

**Comment by prescottprue** [comment]
Closing since I believe this is due to old versions - feel free to reach out if you are still not able to access statics in newer versions.

Thanks for reporting

**Comment by Peeeep** [comment]
Hi there, I can't manage to get any statics in 0.10.0 either, but had no problem in a different app running 0.8.0... Using react-native-firebase in both cases.

**Comment by prescottprue** [comment]
@Peeeep Did you try using the statics directly off of the react-native-firebase instance? I am thinking that may be the pattern moving forward instead of passing them through the extended instance

**Comment by Peeeep** [comment]
Yes, and that works just fine, but I would prefer passing both firebase & firestore through the extended instance, as this makes it trivial to exchange react-native-firebase with the javascript (web) implementation in the future. We plan on creating a pwa version of our rn app and could entirely reuse our redux saga implementation.

I've come up with the following for now:
```js
import '@react-native-firebase/auth';
import '@react-native-firebase/firestore';
import '@react-native-firebase/...';

import rnFirebase from '@react-native-firebase/app';
import {createFirebaseInstance} from 'react-redux-firebase';
import {createFirestoreInstance} from 'redux-firestore';

export default function configureFirebase(dispatch) {
  const rrfConfig = {...};

  const firebase = rnFirebase.app();

  createFirebaseInstance(firebase, rrfConfig, dispatch);
  const firestoreExtended = {
    ...createFirestoreInstance(firebase, rrfConfig, dispatch),  // redux-firestore helpers
    ...rnFirebase.firestore, // statics
  };

  firebase.extendApp({firestoreExtended});

  return firebase;
}
```
This way I can access the redux-firestore helpers `firebase.firestoreExtended.setListener()`, statics `firebase.firestoreExtended.FieldValue.serverTimestamp()` and – if ever needed – the rnfirestore instance (without the statics)  `firebase.firestore()`.

**Comment by prescottprue** [comment]
@Peeeep Nice! Thanks for posting - we may want to add this to the react-native section of the docs
