### ISSUE TITLE
Requesting a non-existing document doesn't update data with null

### ISSUE THREAD

**Issue by compojoom** [prescottprue/redux-firestore#179]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
I'm requesting a document from a collection. When the document is non-existing the payload has data null and oardered [], but the data reducer doesn't update with a null value for the requested document. The ordered reducer on the other hand ads an entry [{id: 'non-existing-doc'}]

I'm checking with a HOC to see if a document exist. If I'm getting back null, next time I render I don#t need to wait for the requested prop to finish - I could directly display the data. But since there is no null value in the store, I have to wait on the cached value of requested.

**What is the expected behavior?**
I would expect the store to update with a null value

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
I think that it used to work.

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by compojoom** [comment]
and actually. It updates ordered only if ordered has a document. If I first request a document that exist and then request a non-existing doc, then ordered gets updated with the id of the non-existing document.

If I request non-existing documents - ordered never updates with the id of the non-existing documents.

**Comment by compojoom** [comment]
The problem seems to come from this line in the data reducer:
const data = docName ? get(payload.data, docName) : payload.data;

I do have a docName, but the payload.data is null
So get tries to get the document, it cannot find anything and returns undefined as we haven't specified a default value. 

@prescottprue do you think that we should pass the payload.data as a default value for get? Or do we have to deal with 

```
export function dataByIdSnapshot(snap) {
  const data = {};
  if (snap.data && snap.exists) {
    data[snap.id] = snap.data();
  } else if (snap.forEach) {
    snap.forEach(doc => {
      data[doc.id] = doc.data() || doc;
    });
  }
  return size(data) ? data : null;
}
```

and change the return to something like   return size(data) ? data : snap.id ? {[snap.id]: null} : null;

**Comment by prescottprue** [comment]
That seems to make sense, and I don't think it should impact anything - did you want to make a PR with the updates?

**Comment by compojoom** [comment]
Which one would you prefer? get by specifying a payload.data as default value or return where we add the snap.id?

**Comment by prescottprue** [comment]
I think the return is a little better

**Comment by bcgilliom** [comment]
Is there an update on this? I just ran into this exact problem on  `"react-redux-firebase": "2.2.6", "redux-firestore": "^0.7.0"`

**Comment by compojoom** [comment]
I haven't been able to create a pull request. @bcgilliom - do you want to jump in?

**Comment by bcgilliom** [comment]
Yeah, I think I can do that. It looks like the fix above sets data[id] to null as expected. What's the desired behavior for ordered? The (somewhat strange) behavior described above still happens. To me, it seems like a doc that doesn't exist should never be added to ordered, but I'm not sure if that has other consequences...

The logic in question looks to be in orderedReducer -> writeCollection:

```
if (meta.doc && collectionStateSize) {
    // Update item in array
    return updateItemInArray(collectionState, meta.doc, item =>
      mergeObjects(item, action.payload.ordered[0]),
    );
  }
```
Maybe that should check if `action.payload.ordered[0]` is empty and return existing state if so? 

I made a PR with the above - just let me know if that should do something different. I'm now using my fork in my project and it seems OK so far.

**Comment by prescottprue** [comment]
Great team work on this @bcgilliom and @compojoom! Really glad to see how simple the solution was. Merged the PR with the fix.

**Comment by compojoom** [comment]
Glad that we have one less bug to drag us down :)
