### ISSUE TITLE
bug or odd behavior: unmerged default config constants

### ISSUE THREAD

**Issue by rscotten** [prescottprue/redux-firestore#184]
**What is the current behavior?**

The default config constants are not merged into the main config object when using `createFirebaseInstance()` in `createFirebaseInstance.js`.  Instead, in `src/actions/firestore.js` we have `firebase._.config.defaultConfig`.  

**What is the expected behavior?**

The `defaultConfig` object from `constants.js` should be merged into `firebase._.config` in `createFirebaseInstance.js` -> `createFirebaseInstance()`. In other words, change line 20 in `createFirestoreInstance.js` from

`config: { defaultConfig, ...configs },`

to

`config: { ...defaultConfig, ...configs },`

**Which version of redux-firestore are you using? What about other dependencies?**

Tested on version 0.7.*.

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**

All environments and browsers.

**Minimal demo to reproduce issue (using [codesandbox](https://codesandbox.io/) or similar)**

**Comment by rscotten** [comment]
Fix added in PR #185

**Comment by prescottprue** [comment]
Not intentional from what I can remember. Great find!
