### ISSUE TITLE
Passing a date to startAt query crashes library

### ISSUE THREAD

**Issue by nemo** [prescottprue/redux-firestore#186]
**What is the current behavior?**

[arrayToStr](https://github.com/prescottprue/redux-firestore/blob/7ed329033d7d2627f62833f9b11f3ed0e5f90455/src/utils/query.js#L150) function tries to call `map` on any value that isn't a string, which breaks when the value is a Date object.

**What is the expected behavior?**

It should call `toString` on the date to resolve this issue.

**Which version of redux-firestore are you using? What about other dependencies?**
3.0.0

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**
All.

**Comment by prescottprue** [comment]
Released your fix in [v0.7.2](https://github.com/prescottprue/redux-firestore/releases/tag/v0.7.2). Also added a case to cover it in the tests. Thanks for making the PR!
