### ISSUE TITLE
Error: Collection can only be run on a document

### ISSUE THREAD

**Issue by daniely93** [prescottprue/redux-firestore#192]
**What is the current behavior?**
I receive an error when I navigate directly to any page except '/',
"Error: Collection can only be run on a document. Check that query config for subcollection: "userGuests" contains a doc parameter."
My collection 'userGuests' contains few docs.

**What is the expected behavior?**
To enter any page directly and not from the homepage

**Which version of redux-firestore are you using? What about other dependencies?**
I used 0.7.0, updated to 0.7.2 and still receiving this error.
react-redux@5.1.1
react-redux-firebase@2.1.6
firebase@5.2.0
redux@4.0.1

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**
Chrome / Firefox
It worked when I didn't have subcollections, when I started to add the problem started.

**Comment by taylorbourne** [comment]
I think I just ran into this same issue.. 
```
firestoreConnect([
    { collection: "parties", subcollections: [{ collection: "guests" }] }
  ]),
```
Throws the same error you listed.. I know that each of my `party` collections has at least one guest.

**Comment by prescottprue** [comment]
@taylorbourne You must provide `doc` as well. Subcollections are under a document, which is what the error is indicating.

@daniely93 This error comes from not passing a `doc` setting when creating a query. In order to investigate further I would need code that replicates the issue - feel free to start with [the simple example on code sandbox](https://codesandbox.io/s/xpq3784jvw).

**Comment by daniely93** [comment]
> @taylorbourne You must provide `doc` as well. Subcollections are under a document, which is what the error is indicating.
> 
> @daniely93 This error comes from not passing a `doc` setting when creating a query. In order to investigate further I would need code that replicates the issue - feel free to start with [the simple example on code sandbox](https://codesandbox.io/s/xpq3784jvw).


This is how I export:
`export default compose(
    connect((state, props) => ({
        auth: state.firebase.auth,
        guests: state.firestore.ordered.guests,
        tables: state.firestore.ordered.tables,
        settings: state.settings
    })),
    firestoreConnect(props => [{ collection: 'guests', orderBy: ['expected', 'desc'], doc: props.auth.uid, subcollections: [{ collection: 'userGuests' }], storeAs: 'guests' }])
)(ArrangeGuests);`

I need the collection that contains all my docs inside by user ID, is it a bad way to handle that?

**Comment by prescottprue** [comment]
@daniely93 It seems like you are not waiting for data (in this case auth uid) to load before creating your query - this is [outlined in the queries section of the docs](http://react-redux-firebase.com/docs/queries.html#loading) as well as [in the state based query example](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery). You will most likley want something like so:

```js
const enhance = compose(
  connect((state) => ({ auth: state.firebase.auth })),
  // show loading spinner while auth is loading
  spinnerWhileLoading(['auth']),
  // set/unset listener to "projects" path on component mount/unmount
  firebaseConnect((props) => [{
    collection: 'guests',
    orderBy: ['expected', 'desc'],
    doc: props.auth.uid,
    subcollections: [{ collection: 'userGuests' }],
    storeAs: 'guests'
  }]),
  // map projects from redux state to props
  connect(({ firebase: { data: { projects } } }) => ({
    guests: state.firestore.ordered.guests,
    tables: state.firestore.ordered.tables,
    settings: state.settings
  })),
  // show loading spinner while guests are loading
  spinnerWhileLoading(['guests']),
)
```

**Comment by daniely93** [comment]
> @daniely93 It seems like you are not waiting for data (in this case auth uid) to load before creating your query - this is [outlined in the queries section of the docs](http://react-redux-firebase.com/docs/queries.html#loading) as well as [in the state based query example](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery). You will most likely want something like so:
> 
> ```js
> const enhance = compose(
>   connect((state) => ({ auth: state.firebase.auth })),
>   // show loading spinner while auth is loading
>   spinnerWhileLoading(['auth']),
>   // set/unset listener to "projects" path on component mount/unmount
>   firebaseConnect((props) => [{
>     collection: 'guests',
>     orderBy: ['expected', 'desc'],
>     doc: props.auth.uid,
>     subcollections: [{ collection: 'userGuests' }],
>     storeAs: 'guests'
>   }]),
>   // map projects from redux state to props
>   connect(({ firebase: { data: { projects } } }) => ({
>     guests: state.firestore.ordered.guests,
>     tables: state.firestore.ordered.tables,
>     settings: state.settings
>   })),
>   // show loading spinner while guests are loading
>   spinnerWhileLoading(['guests']),
> )
> ```

Few things, why firebaseConnect and not firestoreConnect?
what is the usage of "{ firebase: { data: { projects } }" (why do I need props here and not state?)?
spinnerWhileLoading is not defined, I even tried to use my own spinner but it won't work.

Appreciate your help.

**Comment by prescottprue** [comment]
1. firebaseConnect -> firestoreConnect (just a typo, my bad. Fixed.)
2. The usage of the destructuring is off of state (i.e. `state.firestore.ordered.guests`, I just didn't remove the destructuring in my example by accident. Fixed that)
3. `spinnerWhileLoading` is not defined because you didn't define it or import it from anywhere. The [link I provided before](http://react-redux-firebase.com/docs/queries.html#loadingHOCs) has a sample which includes`spinnerWhileLoading` - it is a simple higher order component to check for loading state of a list of props

A good hint on things being undefined is that it hasn't been imported at the top of the file - now in the days of modules/ES6 there is often not global variables, especially not from libraries.

**Comment by daniely93** [comment]
> 1. firebaseConnect -> firestoreConnect (just a typo, my bad. Fixed.)
> 2. The usage of the destructuring is off of state (i.e. `state.firestore.ordered.guests`, I just didn't remove the destructuring in my example by accident. Fixed that)
> 3. `spinnerWhileLoading` is not defined because you didn't define it or import it from anywhere. The [link I provided before](http://react-redux-firebase.com/docs/queries.html#loadingHOCs) has a sample which includes`spinnerWhileLoading` - it is a simple higher order component to check for loading state of a list of props:
>    ```js
>    import { get, some } from 'lodash'
>    import LoadingSpinner from 'components/LoadingSpinner' // or wherever your spinner component is
>    import { isLoaded } from 'react-redux-firebase/lib/helpers'
>    import { compose, branch, renderComponent } from 'recompose'
>    
>    // HOC that shows a component while condition is true
>    export function renderWhile(condition, component) {
>      return branch(condition, renderComponent(component))
>    }
>    
>    // HOC that shows loading spinner component while list of propNames are loading
>    export function spinnerWhileLoadingpropNames {
>      return renderWhile(
>        props => some(propNames, name => !isLoaded(get(props, name))),
>        LoadingSpinner
>      )
>    }
>    ```
> 
> A good hint on things being undefined is that it hasn't been imported at the top of the file - now in the days of modules/ES6 there is often not global variables, especially not from libraries.

I tried to import everything, but still can't fix it.
I will write here my code (deleted irrelevant code), I would like to keep reading about it but if you can guide me with a solution I will appreciate it.

`import React, { Component } from 'react';
import { compose } from 'redux';
import { connect } from 'react-redux';
import { firestoreConnect } from 'react-redux-firebase';
import styles from './ArrangeGuests.module.css';
import Spinner from '../spinner/Spinner';

class ArrangeGuests extends Component {
    componentDidUpdate(prevProps) {
        if (this.props.tables !== prevProps.tables) {
            const { firestore, auth, tables, guests } = this.props;
            // I do here some checks & create an array of tables & tables
        }
    }

    getTableGuests = (tableGuests) => { 
        const { guests } = this.props;
        return <ul>
           // will return ul with guets
        </ul>
    }

    onGuestDelete = async (id) => {
        // will delete guest
    }

    render() {
        const { guests, tables, auth } = this.props;
        if (!tables) {
            return <Spinner />
        }
        return (
            <div style={{ marginTop: '70px' }}>
                
            </div>
        )
    }
}

const enhance = compose(
    connect((state) => ({ auth: state.firebase.auth })),
    Spinner,
    firestoreConnect((props) => [{
        collection: 'guests',
        orderBy: ['expected', 'desc'],
        doc: props.auth.uid,
        subcollections: [{ collection: 'userGuests' }],
        storeAs: 'guests'
    },
    {
        collection: 'guests',
        orderBy: ['relation', 'desc'],
        doc: props.auth.uid,
        subcollections: [{ collection: 'userTables' }],
        storeAs: 'tables'
    }]),
    connect((state) => ({
        guests: state.firestore.ordered.guests,
        tables: state.firestore.ordered.tables,
        settings: state.settings
    })),
)

export default enhance(ArrangeGuests);`

**Comment by prescottprue** [comment]
Are you sure that you are waiting for the auth data to load before using it create a query? The example you provided seems that it wouldn't fully work since Spinner is a component, not an HOC, but not sure without more context. If you could share a codesandbox or similar where the code could e run, that would be helpful.

**Comment by daniely93** [comment]
> Are you sure that you are waiting for the auth data to load before using it create a query? The example you provided seems that it wouldn't fully work since Spinner is a component, not an HOC, but not sure without more context. If you could share a codesandbox or similar where the code could e run, that would be helpful.

Thanks for your help, now it's working!

**Comment by nwaughachukwuma** [comment]
> @taylorbourne You must provide `doc` as well. Subcollections are under a document, which is what the error is indicating.
> 
> @daniely93 This error comes from not passing a `doc` setting when creating a query. In order to investigate further I would need code that replicates the issue - feel free to start with [the simple example on code sandbox](https://codesandbox.io/s/xpq3784jvw).

Hi @prescottprue so I provided a parent `doc` reference when listing subcollections but got same error, when subcollection doesn't exists or isn't created yet. Let me explain a little further.

So say I have an application with a users collection where a user can send friend requests to other users. We are saving the sent  friend requests as a subcollection `sentFriendRequests`, received requests as `friendRequests` and accepted requests as `friends`. But this subcollections are created upon initiation by the user. So for a new user without any friend, who hasn't received any friend request, but who has sent a friend request to another user, if I do
```
firestore.get({ 
      collection: 'users',
      doc: userAuth.uid,
      subcollections: [
          {
               collection: 'sentFriendRequests'
          }
      ]
 });
```
It works and returns the expected user collections with the sentFriendRequests subcollection as part of it. On the other hand, if I do
```
firestore.get({ 
      collection: 'users',
      doc: userAuth.uid,
      subcollections: [
             {
                collection: 'sentFriendRequests'
             },
             {
                 collection: 'friends'
             }
        ]
});
```
remember that the user has no friends yet, this throws the same error by @daniely93.

But this doesn't happen for a string equivalent get operation. So this:
```
firestore.get(`users/${auth.uid}/friends`);
firestore.get(`users/${auth.uid}/sentFriendRequests`);
```
works without any issue whether `friends` subcollection exist or not. I think the same logic should be applied to  firebaseConnect, and the listener methods (onSnapShot included)

**Comment by prescottprue** [comment]
@nwaughachukwuma that is actually not what providing multiple collections to `subcollections` does - it navigates lower in the subcollection tree. `get` actually only ever excepts one listener config, never more than one, regardless of if you use the string notation or the object notation. That means, that you need two `get` calls to attach two different listeners as you mentioned worked.

If you provide multiple subcollections without including `doc` on the first in the array, you will always get this error. That is because you would get a similar error trying to do:
```js
// NOT VALID!!
firebase.firestore().collection('users').doc(auth.uid).collection('sendFriendRequests').collection('friends')
// matches
{
      collection: 'users',
      doc: userAuth.uid,
      subcollections: [
             {
                collection: 'sentFriendRequests'
             },
             {
                 collection: 'friends'
             }
        ]
}
```

**Comment by jakebern** [comment]
@prescottprue I'm also having this issue (#223)

I'm setting "[attachAuthIsReady: true](http://react-redux-firebase.com/docs/recipes/auth.html#wait-for-auth-to-be-ready-ssr)" - I assume that take care of the issue of props not being available on load - please correct me if I'm wrong.

This error only happens for me on signOut event - is it possible that attachAuthIsReady only triggers promise on signIn event?

**Comment by prescottprue** [comment]
@jakebern That is actually not what `attachAuthIsReady` was created for - it was created to attach a promise to be used in SSR.  With components you should be checking for existence of `state.firebase.auth.uid`.

**Comment by nwaughachukwuma** [comment]
> @nwaughachukwuma that is actually not what providing multiple collections to `subcollections` does - it navigates lower in the subcollection tree. `get` actually only ever excepts one listener config, never more than one, regardless of if you use the string notation or the object notation. That means, that you need two `get` calls to attach two different listeners as you mentioned worked.
> 
> If you provide multiple subcollections without including `doc` on the first in the array, you will always get this error. That is because you would get a similar error trying to do:
> 
> ```js
> // NOT VALID!! You cannot do a collection of a collection or multiple listeners in one call
> firebase.firestore().collection('users').doc(auth.uid).collection('sendFriendRequests').collection('friends')
> // matches
> {
>       collection: 'users',
>       doc: userAuth.uid,
>       subcollections: [
>              {
>                 collection: 'sentFriendRequests'
>              },
>              {
>                  collection: 'friends'
>              }
>         ]
> }
> ```
> 
> Instead you should do:
> 
> ```js
> // String notation
> firestore.get(`users/${auth.uid}/friends`);
> firestore.get(`users/${auth.uid}/sentFriendRequests`);
> 
> // OR
> // Object notation
> const friendsListenerConfig  = {
>       collection: 'users',
>       doc: userAuth.uid,
>       subcollections: [
>              {
>                  collection: 'friends'
>              }
>         ]
> }
> const sentRequestsListenerConfig = {
>       collection: 'users',
>       doc: userAuth.uid,
>       subcollections: [
>              {
>                 collection: 'sentFriendRequests'
>              }
>         ]
> }
> firestore.get(friendsListenerConfig);
> firestore.get(sentRequestsListenerConfig);
> ```

@prescottprue, one other thing I noticed following your approach (not sure there's any other) is that things crash when the subcollection does not exist. Say for example: 

```
firestore.get({ 
      collection: 'users',
      doc: userAuth.uid,
      subcollections: [
             {
                collection: 'sentFriendRequests'
             }
        ],
      where: ['userId', '==', 'someOtherUid']
});

```
If sentFriendRequests subcollection doesn't yet exit, it throws the error `undefined is not an object (evaluating 'subcollections.sentFriendRequest')` We are dynamically creating the subcollections, can it not just return null/undefined when it's not there yet?

**Comment by prescottprue** [comment]
Going to close this issue since it seems to be misunderstanding of the API. Thanks to all for reaching out - knowing this input helps shape future api changes

**Comment by pushkars1** [comment]
Error: Collection can only be run on a document. Check that query config for subcollection: "photos" contains a doc parameter.

useFirestoreConnect([
    {
      collection: 'users',
      doc: auth.uid,
      subcollections: [{ collection: 'photos' }],
      storeAs: 'photos'
    }
  ]);

  const photos = useSelector(state => state.firestore.ordered.photos);


on reloading the page http://localhost:3000/settings/photos, i am getting the following error. can anyone help me out with this?

**Comment by daniely93** [comment]
> Error: Collection can only be run on a document. Check that query config for subcollection: "photos" contains a doc parameter.
> 
> useFirestoreConnect([
> {
> collection: 'users',
> doc: auth.uid,
> subcollections: [{ collection: 'photos' }],
> storeAs: 'photos'
> }
> ]);
> 
> const photos = useSelector(state => state.firestore.ordered.photos);
> 
> on reloading the page http://localhost:3000/settings/photos, i am getting the following error. can anyone help me out with this?

Show me your code.

**Comment by daniely93** [comment]
> Error: Collection can only be run on a document. Check that query config for subcollection: "photos" contains a doc parameter.
> 
> useFirestoreConnect([
> {
> collection: 'users',
> doc: auth.uid,
> subcollections: [{ collection: 'photos' }],
> storeAs: 'photos'
> }
> ]);
> 
> const photos = useSelector(state => state.firestore.ordered.photos);
> 
> on reloading the page http://localhost:3000/settings/photos, i am getting the following error. can anyone help me out with this?

I can see you use React Hooks, I haven't used Firebase & Hooks new library so far, but I can tell you that my problem was that auth.uid was undefined, my old solution was:
`firestoreConnect(props => {
   if(!props.auth.uid) return [];
   return [
     // all collections
   ]
}`

I suggest you to debug it using useEffect(() => console.log(photos), [photos]) maybe it'll help you to figure out.

**Comment by kevincharless** [comment]
Hello, i think you should make the doc become a string.
i had the same issue and i fix it by changing the doc to string.

useFirestoreConnect([
{
collection: 'users',
doc: `${auth.uid}`,
subcollections: [{ collection: 'photos' }],
storeAs: 'photos'
}
]);
