### ISSUE TITLE
Parameter 'queryOption' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by GustekDev** [prescottprue/redux-firestore#194]
**What is the current behavior?**

After adding `redux-firestore` with `yarn add redux-firestore` and adding `firestore` reducer , project is not compiling any more and I get an error
```
node_modules/redux-firestore/index.d.ts
(100,39): Parameter 'queryOption' implicitly has an 'any' type.
```

**What is the expected behavior?**

It should compile

**Which version of redux-firestore are you using? What about other dependencies?**
```
{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "@types/react-redux": "^7.0.5",
    "@types/react-router-dom": "^4.3.1",
    "@types/yup": "^0.26.12",
    "firebase": "^5.8.4",
    "formik": "^1.5.1",
    "hoist-non-react-statics": "^3.3.0",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-redux": "^6.0.1",
    "react-redux-firebase": "^2.2.6",
    "react-router-dom": "^4.3.1",
    "react-scripts-ts": "3.1.0",
    "redux": "^4.0.1",
    "redux-firestore": "^0.7.2",
    "redux-thunk": "^2.3.0",
    "yup": "^0.27.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^24.0.6",
    "@types/node": "^11.9.5",
    "@types/react": "^16.8.4",
    "@types/react-dom": "^16.8.2",
    "redux-devtools-extension": "^2.13.8",
    "typescript": "^3.3.3333"
  }
}
```
ts config
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

```
**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**

First time I'm using this project

**Minimal demo to reproduce issue (using [codesandbox](https://codesandbox.io/) or similar)**

Tried to set it up in codesandbox but seems that it does not show build errors from typescript.

**Comment by prescottprue** [comment]
@GustekDev Can you provide how you are actually importing the code? I have imported it into a number of other TS projects without issues, but maybe it is a difference in settings. You could turn off `noImplicitAny`, is there a reason you have it on?

**Comment by GustekDev** [comment]
Do you mean the import line in reducer for example?

```
import { combineReducers } from 'redux';
import { firebaseReducer } from 'react-redux-firebase';
import { firestoreReducer } from 'redux-firestore'

const rootReducer = combineReducers({
    firebase: firebaseReducer,
    firestore: firestoreReducer,
//other reducers...
  })
  
  export default rootReducer;

```

I like my types to be known, and avoid uses of `any` where possible, that config option helps with this.
I did disable it temporarily as workaround for this issue but I hope I will be able to enable it back.

**Comment by GustekDev** [comment]
I assume it should be type annotated as string based on this comment

https://github.com/prescottprue/redux-firestore/blob/7ed329033d7d2627f62833f9b11f3ed0e5f90455/src/actions/firestore.js#L141

**Comment by prescottprue** [comment]
Thanks for the PR
