### ISSUE TITLE
feat(query): support array_contains in where query

### ISSUE THREAD

**Issue by ashton721** [prescottprue/redux-firestore#198]
Firestore allows you to query an array field based on its contents but it doesn't seem to be available in this package. 

When attempting to do a query like where: ['arrayField', 'array_contains', valueToLookFor]
I get the following error:  @firebase/firestore: Firestore (5.5.9): FIRESTORE (5.5.9) INTERNAL ASSERTION FAILED: Unknown relation: array_contains 

So I assume it currently isn't supported. Are there any plans to implement this?

**Comment by prescottprue** [comment]
It isn't currently supported, but it definitely should be! Open to a PR if anyone gets to it, otherwise I will try to get to it when I can. Thanks for reporting!

**Comment by rscotten** [comment]
@ashton721 @prescottprue I use `array-contains` with a hyphen on 0.7.3 and it works for me

**Comment by GitHubGreg** [comment]
Thanks for the note that array-contains works. @prescottprue should we expect this to change to array_contains in the future?

**Comment by prescottprue** [comment]
@GitHubGreg the goal is to keep things as close to the Firebase API as possible, and since in [their examples in the docs they use `array-contains`](https://firebase.google.com/docs/firestore/query-data/queries#array_membership), the current plan will be to stick with that. Did you find `array_contains` somewhere in the Firebase docs?

**Comment by ashton721** [comment]
Looks like the confusion is due to inconsistently in the firebase docs. Their description says array_contains but their code example says array-contains. Thanks for helping me figure it out

**Comment by GitHubGreg** [comment]
Yeah I was following their docs. Thanks guys.

**Comment by prescottprue** [comment]
Oh great to know, we should report an issue on their docs!
