### ISSUE TITLE
Trying use getFirebase and getFirestore, but catch an error

### ISSUE THREAD

**Issue by PeterPil** [prescottprue/redux-firestore#200]
I use the newest version of  react-redux-firebase: "^3.0.0-alpha.10" and want use getFirestore and getFirebase, but i can't use it, because get an error: "Firebase instance does not yet exist. Check your compose function". I found issue #13 but I don't understend how implement it in my code. Help me to solve that, thanks

**Comment by prescottprue** [comment]
Responded to [663 that you posted in react-redux-firebase](https://github.com/prescottprue/react-redux-firebase/issues/663). Going to close since this has also been asked in [635](https://github.com/prescottprue/react-redux-firebase/issues/635).
