### ISSUE TITLE
Or style query example firestore

### ISSUE THREAD

**Issue by donvanderkrogt** [prescottprue/redux-firestore#205]
I'm having trouble to perfom multiple queries and compose the data like in the documentation: `['sally', 'john', 'peter'].map(friendId => ({
                             collection: 'users',
                             where: [
                                    ['id', '==', friendId],
                                    ['isOnline', '==', true]
                             ]
                            storeAs: 'onlineFriends'
}));`

Do you wrap the firestore.get() around this? Because if I do so I get the error "Collection and/or Doc are required parameters within query definition object"

Thanks for the help!

**Comment by prescottprue** [comment]
@donvanderkrogt I believe your storeAs will cause all of the values from each query to run over each other instead of getting all three results - which could be the reason for your issue.

If you stored each query in a different location in redux state (i.e. a dynamic storeAs based on which item you are on) then they can be combined later.

**Comment by prescottprue** [comment]
Here is an example:

```js
import { flatten } from 'lodash'

const friendsToCombine = ['sally', 'john', 'peter']
export default compose(
  firebaseConnect(({ projectId }) =>{
    return friendsToCombine.map(friendId => ({
       collection: 'users',
       where: [ ['id', '==', friendId], ['isOnline', '==', true] ],
       storeAs: `${friendId}-onlineFriends`
    }))
  }),
  connect(({ firebase: { data } }, { projectId }) => ({
    friends: flatten(friendsToCombine.map((friendId) => get(data, `${friendId}-onlineFriends`)))
  })),
)
```


You could also make use of [lodash's uniqBy](https://lodash.com/docs/4.17.11#uniqBy) if you don't want repeats of users.
