### ISSUE TITLE
[Question]: Hook into LISTENER_RESPONSE action?

### ISSUE THREAD

**Issue by Wgil** [prescottprue/redux-firestore#213]
Hello,

I would like to know if there's a way to "hook" into the `LISTENER_RESPONSE` action so I can dispatch another actions based on the data returned by firestore and handled by `LISTENER_RESPONSE`. What I would like to achieve is to filter the data I'm getting using `firestoreConnect` into more specific collections.

Any help would be appreciated.

**Comment by esbenvb** [comment]
I had the same issue yesterday, ended up with this solution:

https://github.com/prescottprue/react-redux-firebase/issues/691#issuecomment-487287309

**Comment by Wgil** [comment]
@esbenvb thanks for pointing me to your solution, I'll get to you my final solution :)

**Comment by prescottprue** [comment]
Going to close for now since there is a posted solution
