### ISSUE TITLE
TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by NischalShahi** [prescottprue/redux-firestore#226]
I tried running example/basic but i got the following error.

![Screenshot from 2019-07-07 15-57-29](https://user-images.githubusercontent.com/37703654/60766937-10fa6d80-a0d0-11e9-98aa-966de7d98ec3.png)

**Comment by illuminist** [comment]
Make sure you setup redux store correctly and use correct react-redux version that compatible with react-redux-firebase version.
