### ISSUE TITLE
Support for querying timestamp from firestore

### ISSUE THREAD

**Issue by BenKalungi** [prescottprue/redux-firestore#229]
**What is the feature?**

**What version would this apply to?**

**Do you have thoughts/examples on how the feature would be used (i.e. API)?**

**Comment by BenKalungi** [comment]
I have some posts in my firestore database but I would like to include the timestamp for each post
For instance
`!isEmpty(posts) && posts.map(
    post => (
   <div key={post}>
<p>{post.title}</p>
<p>{post.body}</p>
<p>{post.date}</p>
</div>
)
)`

**Comment by prescottprue** [comment]
The value should be getting passed for the query with a timestamp. Just so I fully understand, could you provide an example of the feature you are describing?

Going to close for now, but will reopen provided an example
