### ISSUE TITLE
state.firestore.status.requesting has elements set to true, even after data is present in state.firestore.data

### ISSUE THREAD

**Issue by esbenvb** [prescottprue/redux-firestore#232]
**What is the current behavior?**
Some times, like 1% or 2% of the times I load a screen in my React Native app, one of the documents that are connected with `firestoreConnect` to that screen, still has `true` as `requesting` status.

I currently show a spinner on top of the UI if any document is `true` in the `requesting` object. And `false` in the `requesting` object.

This issue is very hard to reproduce, especially when the React Native Debugger is enabled. But I managed once to inspect the redux store, and I can see that the path which is still requesting, has got its data in `state.firestore.data`, and the UI has all its content, below the spinner I show.

I can see the `LISTENER_RESPONSE` action for the path that was listed as requesting, in the action history, and as said, the content is present at the `storeAs` key in the action. 

I apologize for the vague description and debugging, and missing reproduction steps, but it's only happening about 1% of the times I load a screen, so it's really hard to debug.

**What is the expected behavior?**
I expect `state.firestore.status.requesting` to correctly reflect the current status, so I can use it for indicating whether data is currently being loaded

**Which version of redux-firestore are you using? What about other dependencies?**

```
    "react-native-firebase": "^5.3.1",
    "react-redux": "^5.1.1",
    "react-redux-firebase": "^2.2.6",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-firestore": "^0.7.2",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"
```
Also tested with newest versions `redux-firestore@0.8.0` and `react-native-firebase@2.4.0`, still having the issue :( 

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**
React native 0.59.10 both Android 5-9 and iOS 12

Here is a snapshot of my `firestore` branch of the state:

```js
  firestore: {
    status: {
      requesting: {
        'users/iAWZXwc2MoaYjPD5FJIunwmipgC2/attributes/favoriteTeams': false,
        followingTeams: false,
        tournaments: false,
        'seasons/sr:season:67253/attributes/teams': true,        // THIS IS WRONG
        'localizations/teams/languages/en': false,
        'seasons/sr:season:66441/attributes/teams': false
      },
      requested: {
        'users/iAWZXwc2MoaYjPD5FJIunwmipgC2/attributes/favoriteTeams': true,
        followingTeams: true,
        tournaments: true,
        'seasons/sr:season:67253/attributes/teams': false,    // THIS IS WRONG
        'localizations/teams/languages/en': true,
        'seasons/sr:season:66441/attributes/teams': true
      },
      timestamps: {
        'users/iAWZXwc2MoaYjPD5FJIunwmipgC2/attributes/favoriteTeams': 1565987383715,
        followingTeams: 1565987383727,
        tournaments: 1565987385813,
        'seasons/sr:season:67253/attributes/teams': 1565987385814,
        'localizations/teams/languages/en': 1565987385815,
        'seasons/sr:season:66441/attributes/teams': 1565987385847
      }
    },
    data: {
      tournaments: {
.........
        }
      },
      'localizations/teams/languages/en': {
        expiration: '2020-01-30',
        body: {
........
        }
      },
      'seasons/sr:season:66441/attributes/teams': {
        expiration: null,
        body: {
..............
        }
      }
    },
```

**Comment by prescottprue** [comment]
Thanks for reporting - are you using `storeAs` or no?

**Comment by esbenvb** [comment]
yes I am using storeAs for all documents

**Comment by esbenvb** [comment]
I think I have come closer to the cause of the problem.

In my app, I have an `activeTournament` value in the store, which is used for a selector in a screen that I'm loading. If the screen, after loading, determines that the `activeTournament` in the store is not a valid one, it will fall back to a valid value.

This screen is also `firestoreConnect`ed to a document that has the ID of the `activeTournament` as a document ID.

So, when the screen component is loading, `firestoreConnect` will set up a listener based on the state's `activeTournament` but as soon as the screen is mounted, `componentDidMount` may change the `activeTournament` . Which makes `firestoreConnect` listen to a different document.

Here's what happens in the store actions
![image](https://user-images.githubusercontent.com/426051/63509214-e7f53700-c4db-11e9-8542-0b4d8328b2fb.png)


* First, it will `SET_LISTENER` for `seasons/sr:season:67681/attributes/teams`
* Then `SET_TOURNAMENT` will change the value to `sr:season:66441`
 * And this will cause `firestoreConnect` to run again, and trigger an `UNSET_LISTENER` on `seasons/sr:season:67681/attributes/teams`
* And then a `SET_LISTENER` on `seasons/sr:season:66441/attributes/teams`

This works, and I get the data that I need. However, because `seasons/sr:season:67681/attributes/teams` never got a response before the listener was unset, `state.firestore.status.requsting["seasons/sr:season:67681/attributes/teams"]` is still `true`

So the bug is probably, that `UNSET_LISTENER` does not remove the `requsting` flag for the document's `storeAs` path

**Comment by esbenvb** [comment]
The same thing happens in another screen, that's loading some very big documents (500KB+) from firestore. This screen is also `firestoreConnect`ing the documents based on the `activeTournament` in the redux state. On the screen there's a button that allows the user to switch tournament. If user switches `activeTournament` before the current tournament's documents are loaded, the documents related to that tournament will remain in a `requesting` status, because the listener was unset before document was downloaded (and thereby, before the LISTENER_RESPONSE was fired)

**Comment by prescottprue** [comment]
How are you getting the values from state to add to your query? Can you provide the `firestoreConnect` code?

**Comment by esbenvb** [comment]
Like this.

```ts
export default compose(
  connect(
    mapStateToProps,
    mapDispatchToProps
  ),
  firestoreConnect((props: Props, store: Store<ReduxState>) => {
    const state = store.getState()
    const { activeTournament } = state.general
    if (!activeTournament) {
      return [fq.allTournaments.query()]
    }
    return [
      fq.allTournaments.query(),
      fq.seasonTeams.query(activeTournament.currentSeason.id),
      fq.localizedTeams.query(currentLanguageCode),
    ]
  })
  // @ts-ignore https://github.com/prescottprue/react-redux-firebase/issues/682
)(SignupFollowScreen)
```

`fq` is a module I made with all the queries needed for firestore documents. Example:

```ts
export const seasonTeams: FirestoreQueryItem<ID> = {
  key(id) {
    return `seasons/${id}/attributes/teams`
  },
  query(id: ID) {
    return {
      collection: 'seasons',
      doc: id,
      subcollections: [{ collection: 'attributes', doc: 'teams' }],
      storeAs: this.key(id),
    }
  },
}
```

**Comment by prescottprue** [comment]
@esbenvb good to know, thanks. Saw your PR.

Something to keep in mind is that you should avoid using `store.getState` within your queries since it is known to cause some issues where state changes and does not correctly re-render since there wasn't a props change. It is better to connect to state and pass the values as props:

```js
export default compose(
  connect(
   (state) => ({ activeTournament: state.general.activeTournament }),
    mapDispatchToProps
  ),
  firestoreConnect((props: Props, store: Store<ReduxState>) => {
    if (!props.activeTournament) {
      return [fq.allTournaments.query()]
    }
    return [
      fq.allTournaments.query(),
      fq.seasonTeams.query(activeTournament.currentSeason.id),
      fq.localizedTeams.query(currentLanguageCode),
    ]
  }),
  connect(
   (state) => {
      // data state connection here
   }
  ),
  // @ts-ignore https://github.com/prescottprue/react-redux-firebase/issues/682
)(SignupFollowScreen)
```

This also helps to prevent unnecessary re-renders of `firebaseConnect` as data is received. The re-render of `firebaseConnect` will only happen if the props which are passed to it changed

**Comment by esbenvb** [comment]
Thanks! I'll do that for the future. I was no aware of the pattern where I could have first a `connect` block mapping state to props, then `firestoreConnect` block reading the props and then another `connect` block mapping the firestore state to props

**Comment by prescottprue** [comment]
Closing since it appears that the proposed implementation works as expected
