### ISSUE TITLE
Executing multiple queries does not save results of the previous query

### ISSUE THREAD

**Issue by namankumar** [prescottprue/redux-firestore#237]
**What is the current behavior?**
Executing multiple queries in the same firestoreConnect only preserves the result of the last one. Workaround is to use storeAs but there is a sideeffect. With storeAs, the results from populates are only saved for the very last query. 

I could see in console the queries and populates are executed as expected but the result from the previous query becomes undefined when the result of the next query appears in the console. 

Note that the commonality between my experience and #227 is that our queries were executed on the same collection.

**What is the expected behavior?**
1. ideally, results of the query is preserved without storeAs
2. results of populates is saved for all queries

**Which version of redux-firestore are you using? What about other dependencies?**
0.8.0
  dependencies:
    immer "1.5.0"
    lodash "^4.17.11"
    reduce-reducers "0.4.3"

**Which environments/browsers are affected by this issue? Did this work in previous versions or setups?**
reactjs web, react native in chrome and iphonex
#227 mentions that popultes did work in 0.7.0

**Minimal demo to reproduce issue (using [codesandbox](https://codesandbox.io/) or similar)**

```
const populates  = [{ child: 'activityID', root: 'activities', keyProp: 'key'}]

const mapStateToProps = state => {
  return {
    activities: state.firestore.ordered.act,
    currentActivities: populate(state.firestore, 'currentActivities', populates),
    completedActivities: populate(state.firestore, 'completedActivities', populates)
  }
}

export default compose(
  firestoreConnect(() => [
  {
    collection: 'activities', 
    storeAs: 'act'
  },
  {
    collection: 'users',
    doc: 'IF6HzQjcxjXmlwnDk5wBSYXnXh73', 
    subcollections: [{ collection: 'completedActivities' }],
    populates: populates,
    storeAs: 'completedActivities'
  },
   {
    collection: 'users',
    doc: 'IF6HzQjcxjXmlwnDk5wBSYXnXh73', 
    subcollections: [{ collection: 'currentActivities' }],
    populates: populates,
    storeAs: 'currentActivities'
  },
]),
connect(mapStateToProps)
)(ActScreen)


```

**Comment by prescottprue** [comment]
In v1 (available on the alpha tag) the queries are all stored by their query params and collection/doc name (instead of just collection/doc name as seen in pre v1 versions). As you have noted, you should be able to use `storeAs` for now, but this is actually a big part of why that breaking change is being made.

**Comment by namankumar** [comment]
Thanks for the link, super helpful! Btw, great work on react-redux-firebase!

**Comment by prescottprue** [comment]
Thanks 😄 . No problem at all, thanks for reporting! It is good to know others are experiencing this, it reenforces the choice for the big change in v1.

If you get a chance to check it out, let me know what you think! Feel free to comment back in this issue or reach out over [gitter](https://gitter.im/redux-firebase/Lobby)

**Comment by namankumar** [comment]
Definitely. I think it's fast becoming my go to lib for web/mobile dev now. It really simplifies the need for an ORM, writing your own redux-specific code, and the population capability is just genius 💯 The fact that I have the option of dropping in rn-firebase just makes forward planning so much easier

I'm learning now if the rrf has a principled way of deciding when to return data using store or when to query the database, though I suppose this might be out of scope for the lib. Any tips on how/where I could write code to make this decision would be great. Joining gitter now!

**Comment by prescottprue** [comment]
It does have a "principled way" - and there are even `isLoaded` and `isEmpty` helpers to assist in checking for those state as described in [the queries section of the react-redux-firebase docs](http://react-redux-firebase.com/docs/queries.html).
