### ISSUE TITLE
Not getting data from firestore

### ISSUE THREAD

**Issue by Klabauterman** [prescottprue/redux-firestore#24]
Hi I am trying to use this component in combination with react-redux-firebase, but I did not get any data from my firestore. I am trying different things for one day now, but no luck yet. The authentication is working fine.

I also don't get how collections and documents are handled. In my case -Ktg8j9RjgIvUmCC1iGe references a document. Does it know which is a document or a collection automatically? 

I try to use connect like this:

```
export default connect<StateFromProps, {}, void>(( state: any ) => (
    {
        auth: state.firebase.auth,
        apartmentList: getVal(state.firestore, 'data/users/pLiT8PvTBgbERBwUe8xPByJBtVn1/apartmentList/-Ktg8j9RjgIvUmCC1iGe', 'init')

    }))(
    firestoreConnect(['/users/pLiT8PvTBgbERBwUe8xPByJBtVn1/apartmentList/-Ktg8j9RjgIvUmCC1iGe'])(
        withStyles(styles)(App)
    )
);
```

My setup looks like this:

```
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';
import theme from './theme/theme';

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { createStore, combineReducers } from 'redux';
import { firebaseStateReducer, firestoreReducer, reactReduxFirebase } from 'react-redux-firebase';
import 'firebase/firestore';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import { Provider } from 'react-redux';
import * as firebaseApp from 'firebase/app';
import * as firebase from 'firebase';
import { reduxFirestore } from 'redux-firestore';

const firebaseConfig = {
    ... here is my config...
};

const rrfConfig = {
    userProfile: 'users',
    useFirestoreForProfile: true
};

firebaseApp.initializeApp(firebaseConfig);
firebaseApp.firestore();


const createStoreWithFirebase = reduxFirestore(firebaseApp, {})(
    reactReduxFirebase(firebase, rrfConfig)(createStore)
);

// Add Firebase to reducers
const rootReducer = combineReducers({
    firebase: firebaseStateReducer,
    firestore: firestoreReducer
});

// Create store with reducers and initial state
const store = createStoreWithFirebase(rootReducer, {});

ReactDOM.render(
    <MuiThemeProvider theme={theme}>
        <Provider store={store}>
            <App/>
        </Provider>
    </MuiThemeProvider>,
    document.getElementById('root') as HTMLElement
);
registerServiceWorker();
```

**Comment by Klabauterman** [comment]
What I did not get in the beginning is that i cannot access data of deeper collections by using a string path.

This could be a valid path for the firestoreConnect:
```
let path = {
    collection: 'testcollection',
    doc: 'testdocument',
    subcollections: [{ collection: 'c2', doc: 'd2' }, { collection: 'c3', doc: 'd3' }] 
}
```

**Comment by Venryx** [comment]
Thanks for the hint, @Klabauterman. I was having the same issue, and your approach above worked. (using collection, doc, ... syntax).

@prescottprue Is there a reason users need to use the code above, instead of just using a string path? A string path seems faster and more convenient.

And it's equivalent to the code above, since you can always determine which path-node is a collection or doc based on index. (since firestore requires that paths always follow: collection/doc/collection/doc) Perhaps you want to allow for additional functionality beyond just simple requesting?

Even so, might be worth allowing the string-based shorthand as well, as it covers many simple cases.
