### ISSUE TITLE
propTypes typo on HomePage

### ISSUE THREAD

**Issue by menno11100** [prescottprue/redux-firestore#242]
Home.proptypes = {
  classes: PropTypes.object.isRequired // from enhancer (withStyles)
}

should be:
 
Home.propTypes = {
  classes: PropTypes.object.isRequired // from enhancer (withStyles)
}

**Comment by prescottprue** [comment]
Thanks for reaching out!

Home is no longer used in that example - Not sure why it was still in there, but [the PR for v0.10.0 removes it](https://github.com/prescottprue/redux-firestore/pull/244). It also includes other updates including usage of hooks
