### ISSUE TITLE
Profile data in firestore

### ISSUE THREAD

**Issue by NathHorrigan** [prescottprue/redux-firestore#25]
I've been using Firebase realtime database in my react-native app using `react-redix-firebase` and am  switching to Firestore from RD. I have set the following for my reduxFirebase config:
```
const reduxFirebaseConfig = {
  userProfile: 'users',
  enableRedirectHandling: false,
  useFirestoreForProfile: true
}
```
 but I user data still isn't being put in firestore when I use firebase.updateProfile and there is no firestore.updateProfile - Am I missing something??

**Comment by prescottprue** [comment]
This will be a change in `react-redux-firebase`, but I'll make sure to update this ticket when it is out.

**Comment by prescottprue** [comment]
Work on this has started on this in `react-redux-firebase` - the plan is to release it as part of `beta.18` in the next day or so
