### ISSUE TITLE
id is removed in 'ordered' when an item is added.  

### ISSUE THREAD

**Issue by quintenb** [prescottprue/redux-firestore#252]
When I add an item to the firestore db using the add command:

`firestore.add({ collection: "bookmarks" }, bookmark)`

You see the item is added correctly at first but with the 'createdAt' value still empty.

I use:

`createdAt: firestore.FieldValue.serverTimestamp()`
 
![bug_01](https://user-images.githubusercontent.com/6967754/69485647-aeb5c580-0e42-11ea-9fb0-354fe290f3ad.png)

But when the DOCUMENT_MODIFIED is dispatched and the createdAt is updated in the state, the Id of the document gets removed. 

![bug_02](https://user-images.githubusercontent.com/6967754/69485648-b07f8900-0e42-11ea-9014-584b3e501269.png)

**Comment by prescottprue** [comment]
Thanks for reporting! Seems like that was a recent change to remove merging. I also added a test case to make sure that doesn't happen in the future.

Planning to release in [v0.11.0](https://github.com/prescottprue/redux-firestore/pull/251)

**Comment by jacklimwenjie** [comment]
I found a workaround, which is to always include `id` in the args when adding/updating a doc

**Comment by prescottprue** [comment]
Glad to hear you found a workaround. The [v0.11.0 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.11.0) contains the fix. Please reach out if things don't work as expected, and thanks again for posting
