### ISSUE TITLE
Ordered state doesn't update on deleting an item

### ISSUE THREAD

**Issue by vikramrana** [prescottprue/redux-firestore#256]
**What is the current behavior?**

The data state updates on delete but the ordered state shows no effect.

<img width="1599" alt="Screen Shot 2019-12-06 at 3 03 13 AM" src="https://user-images.githubusercontent.com/15370158/70318684-76649e80-17d5-11ea-9cc5-2b2bf67837ee.png">

**Which version of redux-firestore are you using? What about other dependencies?**

"redux-firestore": "^0.11.0"

**Comment by prescottprue** [comment]
It should be removed in the `LISTENER_RESPONSE` action directly above like so:

![image](https://user-images.githubusercontent.com/2992224/70322604-89d53100-17f8-11ea-9c33-e2f67e1444d1.png)

If it isn't removed in that action dispatch (i.e. if you don't have a listener) the `DOCUMENT_REMOVED` should the remove it ([from this logic](https://github.com/prescottprue/redux-firestore/blob/v0.12.0/src/reducers/orderedReducer.js#L120)), but from the looks of your picture it seems you have a listener attached, is that not what you are seeing?

**Comment by vikramrana** [comment]
Thank you for your response, but maybe I am doing something wrong. 
 I am providing few more screenshots for you to assess.

STEP 1:
I click on an item to remove, the item in the ui stays there. Although the data state updates, there is no response from the listener.

<img width="1469" alt="Screen Shot 2019-12-06 at 12 24 45 PM" src="https://user-images.githubusercontent.com/15370158/70354843-81471f80-1825-11ea-9412-998e5b2bec23.png">

STEP 2:
I click on the same item again and I receive this error which makes sense as the item in the data state becomes null.

<img width="1462" alt="Screen Shot 2019-12-06 at 12 29 11 PM" src="https://user-images.githubusercontent.com/15370158/70354998-eb5fc480-1825-11ea-89c3-5c5dd588c03b.png">

**Comment by vikramrana** [comment]
I was able to solve the issue. Since I already had an id key in my product it wasn't using the auto generated uid as the id. I just changed my id key to companyID and now it works as expected.
