### ISSUE TITLE
Direct Firestore "add", "update", etc. calls fails when signed in

### ISSUE THREAD

**Issue by Venryx** [prescottprue/redux-firestore#26]
I've been updating a project of mine (which uses react-redux-firebase) from firebase to firestore.

So far so good. I've got the sign in system working, and have the data querying code working fine. (as far as I've tested anyway)

I'm now trying to reimplement the data saving/storing code. Because I prefer the direct route for storing data rather than the redux "action" system, I'm using code like this:

```
store.firebase.firestore().collection("users").add({
    first: "Ada",
    last: "Lovelace",
    born: 1815
}).then(()=>console.log("Done")).catch(err=>console.log("Error: " + err))
```

The code above works perfectly when I am not signed in. When I'm signed in, however, the code snippet does nothing. It just returns a promise which never completes.

If I sign back out, it starts working again. If I sign back in, it stops working.

Any idea what could be causing these direct calls to fail?

**Comment by prescottprue** [comment]
@Venryx Not sure what would be causing this, but I will try replicating myself.

**Comment by Venryx** [comment]
Okay, did some primitive debugging (ie. debugger calls all over the place), and found a hint.

In file "webpack:///./node_modules/@firebase/firestore/dist/esm/src/remote/remote_store.js?169f", on lines 466-478, we see this:
```
/**
     * Returns true if the backend can accept additional write requests.
     *
     * When sending mutations to the write stream (e.g. in fillWritePipeline),
     * call this method first to check if more mutations can be sent.
     *
     * Currently the only thing that can prevent the backend from accepting
     * write requests is if there are too many requests already outstanding. As
     * writes complete the backend will be able to accept more.
     */
    RemoteStore.prototype.canWriteMutations = function () {
        return (this.isNetworkEnabled() && this.pendingWrites.length < MAX_PENDING_WRITES);
    };
```

When I place a breakpoint on the "pendingWrites" line, I find that when signed out, `pendingWrites.length` is 0, so the function returns true and the "add" call is executed. When signed in, `pendingWrites.length` is 10 (the max), so the function returns false and the call is dropped/delayed.

So now I need to figure out what those earlier calls are, and why they are failing to complete...

**Comment by Venryx** [comment]
Any luck reproducing the issue?

Not trying to pressure -- just want to know whether it's something in my own code that I need to fix (in which case I can stop delving into the firestore messaging code), or something in the library (in which case I might continue).

**Comment by Venryx** [comment]
I appear to have found the cause:
```
firestoreDB.doc(`userExtras/${userID}`).update({
	permissionGroups: {basic: true, verified: true, mod: false, admin: false},
	joinDate: Date.now(),
});
```

The code above was set to run as soon as the user logged in (for the first time). However, it used the "update" function instead of the "set" function. Using firebase, the same code worked, even if the userExtra/USERID path did not exist yet; however, this version seems to fail if the path does not exist.

Therefore, the calls would get sent to firestore, but firestore either wouldn't respond, or the response was not handled correctly, causing the request to never get removed from the request-buffer (in Network dev-tools, it appears the request was sent and a suitable response; however, the breakpoints were never hit for the code that processes the responses -- even as far back as I could trace the standard stack-trace).

Since the request-buffer has a max length of 10, it would then get full and block further calls.

Everything works as expected when the code is changed to use "set": (with "merge" set to true)
```
firestoreDB.doc(DBPath(`userExtras/${userID}`)).set({
	permissionGroups: {basic: true, verified: true, mod: false, admin: false},
	joinDate: Date.now(),
}, {merge: true});
```

To me, this appears to be a bug in Firestore's web-client. If the "update" call fails to run because the path does not exist, the client should raise some sort of warning or error. Or at the very least, remove the call from the buffer, so that later calls can pass through.

**Comment by Venryx** [comment]
I went ahead and submitted a bug-report. (at https://firebase.google.com/support/contact/bugs-features)

It's possible the issue only comes up in particular circumstances, however. (it's a bit hard to believe they let an issue that large pass testing)

Can someone check if the issue occurs in your project as well -- update failing for non-existent paths, but giving no error or warning message? (and furthermore, blocking later requests if 10+ of these failed calls occur)

Anyway, I'll close the issue since it appears to not be a problem with `redux-firestore` specifically.
