### ISSUE TITLE
how can use getFirestore() inside action in v3 like v2

### ISSUE THREAD

**Issue by knour89** [prescottprue/redux-firestore#262]
in v2 I built the following code but it not working in v3, because of no getFirestore

export const registerUser = data => async (
  dispatch,
  getState,
  getFirebase,
  getFirestore
) => {
  const firebase = getFirebase();
  const firestore = getFirestore();

  try {
    let createdUser = await firebase
      .auth()
      .createUserWithEmailAndPassword(data.email, data.password);
    await createdUser.user.updateProfile({
      displayName: data.displayName
    });

    //init firestore data
    let newUser = {
      displayName: data.displayName,
      createdAt: firestore.FieldValue.serverTimestamp()
    };
    //create new collection users
    await firestore.set(`users/${createdUser.user.uid}`, { ...newUser });
  } catch (error) {
    throw new SubmissionError({
      _error: error.message.replace("signInWithEmailAndPassword failed:", "")
    });
  }
};

**Comment by prescottprue** [comment]
As stated in [836](https://github.com/prescottprue/react-redux-firebase/issues/836) and [785](https://github.com/prescottprue/react-redux-firebase/issues/785) of react-redux-firebase - you can use `getFirebase().firestore()`.
