### ISSUE TITLE
Hooks vs HOC's - Confused :(

### ISSUE THREAD

**Issue by ac205** [prescottprue/redux-firestore#274]
Hey Guys,

I am wondering if someone can help me with my app.

Building an CMS with React-Redux-Firebase.

I am finding it difficult and confusing on how to access my firestore data.

I have main app wrapped in ReactReduxFirebaseProvider with the rrfProps 

Then some components I am using the HOC firestoreConnect to connect to a collection and/or subcollection.

Then for other components I am using useFirestoreConnect and useSelector hooks because I cannot get it to work with a HOC.

Finally I am using thunk and handling actions with getFirestore().....

My question is why is there so many ways to access firestore data, and what is the proper way I should be handling all of this?

Any help for clarification would be very very much appreciated!! Thank you

**Comment by prescottprue** [comment]
`getFirestore` in thunks is NOT for state - it is actually to access the extended firestore instance (similar to Firebase SDK, just with different methods that dispatch actions).

Using `useFirestoreConnect` in your component is the right way to attach listeners on mount/unmount of the component and `useSelector` is the right way to get that data from state. More information and examples are available [in the queries section of the react-redux-firebase docs](http://react-redux-firebase.com/docs/queries.html)

As for what you were saying here:
> Then for other components I am using useFirestoreConnect and useSelector hooks because I cannot get it to work with a HOC.

Not sure what HOC you are referencing, but if you provide code samples (preferably a whole codesandbox, you can use [this one as a starter](https://codesandbox.io/s/71198q6q86)), it will be easier to help debug.

**Comment by ac205** [comment]
Sorry I was referring to { firestoreConnect } from 'react-redux-firebase' but I figured out the issue and was able to get it to work.

But you are saying the useFirestoreConnect + useSelector hook style way is a better choice than using the firestoreConnect HOC style? 

Or will the both result in same overall performance etc?

**Comment by prescottprue** [comment]
@ac205 Both result in the same overall performance, the hooks are just suggested since that is hooks are now a suggested usage pattern in React and may be a little more organized as things scale

**Comment by ac205** [comment]
Awesome thank you so much! Appreciate all the hard work you have put into this :)
