### ISSUE TITLE
How to get to FieldValue?

### ISSUE THREAD

**Issue by 0x80** [prescottprue/redux-firestore#28]
I need access to FieldValue. How can I make this work?

```typescript
const {firestore} = this.props
firestore.update({
      collection: 'userRegistrations',
      doc: documentId,
      {
          isLocked: true,
          lock: {
            owner: auth.uid,
            timestamp: firestore.FieldValue.serverTimestamp(),
          },
      }
    });
```

I can get it by importing firebase at the top of my file, and get it from there, but that seems a bit silly with the instance on props. And it would be easy to make a mistake with shadowing it.

**Comment by prescottprue** [comment]
[The v0.1.0 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.1.0) includes a change where the statics from Firestore are now exported at the top level. That means it is available as you noted in your examples.

Let me know if it doesn't work as expected. Thanks for reporting.

**Comment by mindtricksdev** [comment]
This no longer works after updating to:
"react-redux": "^6.0.0",
"react-redux-firebase": "^3.0.0-alpha.6",
"redux-firestore": "^0.6.3",

**Comment by prescottprue** [comment]
@mindtricksdev Lets open a new issue since that functionality shouldn't have changed at all.

**Comment by mindtricksdev** [comment]
FieldValue property is missing.
