### ISSUE TITLE
Query with limit

### ISSUE THREAD

**Issue by Klabauterman** [prescottprue/redux-firestore#30]
Atm it is not possible to add a limit clause to a query, correct?

**Comment by prescottprue** [comment]
No not yet there isn't. The longer term plan is to include support for passing a ref directly.

**Comment by prescottprue** [comment]
`limit` is supported as part of [`v0.2.0`](https://github.com/prescottprue/redux-firestore/releases/tag/v0.2.0). Thanks for the input and your patience while the library is still young.
