### ISSUE TITLE
endBefore not working as expected

### ISSUE THREAD

**Issue by TrySpace** [prescottprue/redux-firestore#346]
**What is the current behavior?**
Getting to the next pages as described here works: https://www.seedcode.com/paginating-firestore-queries-with-document-snapshot-cursors-and-react-redux-firebase/

Except when I try it with `endBefore` and provide: `getSnapshotByObject(items[0])`, after navigating 3 pages away it returns the  same as the initial query, so it does not select the correct "page".

**What is the expected behavior?**
I'd expect the previous page to be queried, not 3 pages back.
I guess technically it 'ends' 'before' the selected snapshot, but it cuts of the result by the `limit`, but that's not what I want.

**Which version of redux-firestore are you using? What about other dependencies?**
"redux-firestore": "^0.15.0",

**Minimal code to reproduce issue**

```ts

  const posts =  useSelector(({ firestore: { ordered } }: RootState) => ordered[`posts/postsById`])

  const [startCursor, setStartCursor] = useState(null)
  const [endCursor, setEndCursor] = useState(null)

  const nextPage = () => {
    setEndCursor(null)
    setStartCursor(getSnapshotByObject(posts[posts.length - 1]))
  }

  const prevPage = () => {
    setStartCursor(null)
    setEndCursor(getSnapshotByObject(posts[0]))
  }

  const listsQuery: ReduxFirestoreQuerySetting = {
    collection: 'postsById',
    limit,
    orderBy: orderByQuery,
    where: whereQuery,
    storeAs: 'posts/postsById',
    ...(startCursor && { startAfter: startCursor }),
    ...(endCursor && { endBefore: endCursor })  
  }
```

**Comment by TrySpace** [comment]
Trying this as suggested here: https://morioh.com/p/b287c3c0ee1f
Returns all the previously queried items instead of the expected 3... I'm really at a loss here...

```ts

const limit = 3;

const listsQuery: ReduxFirestoreQuerySetting = {
    collection: 'postsById',
    ...(!endCursor && !startCursor && {
      limit,
    }),
    orderBy: orderByQuery,
    where: whereQuery,
    storeAs: 'posts/postsById',
    ...(startCursor && {
      startAfter: startCursor,
      limit,
    }),
    ...(endCursor && {
      endBefore: endCursor,
      limitToLast: limit,
    })
}
```

**Comment by TrySpace** [comment]
Closing because who cares ;p

**Comment by prescottprue** [comment]
@TrySpace - its valid to keep open if this is still an issue you are seeing. How are you selecting these values from state?
