### ISSUE TITLE
bug(orderedReducer): subcollections not updating state.ordered

### ISSUE THREAD

**Issue by joostfarla** [prescottprue/redux-firestore#46]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

I'm using the following listener configuration for syncing a subcollection:

```js
export default compose(
  firestoreConnect(props => [
    {
      collection: 'artists',
      doc: props.artistId,
      subcollections: [
        {
          collection: 'flights',
          orderBy: ['departureMoment'],
        },
      ],
      storeAs: 'flights',
    },
  ]),
  connect(({ firestore }) => {
    return {
      flights: firestore.ordered.flights || [],
    };
  }),
)(FlightPage);
```

The resulting firestore object looks like this:

```js
{
  data: {
    flights: {
      fnEPGX7kGPicCInJkDO3: {...document 1...},
      llOt1wbuTGNMpTHCaurr: {...document 2...}
    }
  },
  ordered: {
    flights: []
  }
}
```

The `ordered` result is an empty array, but the `data` result contains the correct documents.

When I inspect the corresponding `@@reduxFirestore/LISTENER_RESPONSE` action with `redux-logger`, it looks like this:

```js
{
  meta: {...},
  payload: {
    data: {
      fnEPGX7kGPicCInJkDO3: {...document 1...},
      llOt1wbuTGNMpTHCaurr: {...document 2...}
    }
    ordered: [
      {...document 1...},
      {...document 2...}
    ]
  }
}
```

The action payload looks correct. However, the ordered data is not getting mapped correctly.

**What is the expected behavior?**

I would expect the `ordered` result to contain the same documents as the `data` object, but then in an ordered array. Now, the `ordered` array is empty.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
redux: 3.7.2
redux-firestore: 0.2.5
react-redux: 5.0.6
react-redux-firebase: 2.0.0-rc.2

**Comment by prescottprue** [comment]
Fixed as part of [`0.3.1` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.3.1).

Reach out if things are working as expected. Thanks for reporting!
