### ISSUE TITLE
StartAfter does not take into consideration documents with similar values (Skips some documents)

### ISSUE THREAD

**Issue by victorkingi** [prescottprue/redux-firestore#494]
On using startAfter, unlike firestore documentation which requires a document snapshot, this library implementation will skip over documents with a field having similar values i.e. 

Consider a collection `k` with documents:
`(
Document 1: { id: "1234", testVal: 1 }, 
Document 2: { id: "5678", testVal: 1 }, 
Document 3: { id: "9012", testVal: 2 }
)`

First do a normal query on the collection ordering by `testVal` field `asc` and limit 1. With that value, call `startAfter` using the `testVal` just queried as input:
 `{
  collection: 'k',
  orderBy: [['testVal', 'asc']],
  limit: 1,
  startAfter: [1]
},`
will return document 3, skipping document 2. Official firestore documentation, will return all 3 documents since the document object (which is unique) is passed as the argument to startAfter.

A fix would be allowing `startAfter: [documentId: string]` since we know that document ids are always unique or rather allowing document snapshot as an argument.

**Comment by benomatis** [comment]
@victorkingi `startAfter` either takes a value of the field you use in `orderBy`, or a `DocumentSnapshot/QuerySnapshot`. You can use the `getSnapshotByObject` method generate such snapshot object. This is described here: https://github.com/prescottprue/redux-firestore/blob/b65e7a2965369ebe9f5a3bc74b3b4f53d1967c3b/src/utils/query.js#L17-L26
