### ISSUE TITLE
orderBy don't return any results

### ISSUE THREAD

**Issue by QuentinBrosse** [prescottprue/redux-firestore#50]
**Do you want to request a *feature* or report a *bug*?** 

Bug

**What is the current behavior?**

My query return expected results (but not ordered) without the `orberBy` and return an empty result with the `orberBy`.

```js
try {
  const results = await firestore.get({
    collection: 'groups',
    where: [
      ['departureStation.id', '==', departureStationId],
      ['arrivalStation.id', '==', arrivalStationId],
      ['dateTime', '>=', startDate.toDate()],
      ['dateTime', '<=', endDate.toDate()],
    ],
    orderBy: ['dateTime', 'desc'],
  });
  console.log(results); // Return no result (results.empty === true)
} catch (err) {
  console.log(err);
}
```

But without, I have expected results:

```js
try {
  const results = await firestore.get({
    collection: 'groups',
    where: [
      ['departureStation.id', '==', departureStationId],
      ['arrivalStation.id', '==', arrivalStationId],
      ['dateTime', '>=', startDate.toDate()],
      ['dateTime', '<=', endDate.toDate()],
    ],
    // orderBy: ['dateTime', 'desc'],
  });
  console.log(results); // Return expected results (results.empty === false)
} catch (err) {
  console.log(err);
}
```

**What is the expected behavior?**

Unless i'm mistaken, the `orderBy` should not affect the number of retrieved results but only their orders.

I do not know if there is a connection with #46.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

```json
{
    "firebase": "^4.8.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-redux-firebase": "^2.0.1",
    "redux": "^3.7.2",
    "redux-firestore": "^0.2.5",
}
```

All browsers seems to be affected.

Thanks a lot for your help :)

**Comment by prescottprue** [comment]
Did you check that the indexes were set for that type of query? It may be that they are not and an error should be getting thrown to the error state (this is just a guess though).

Either way will try to replicate. Thanks for reaching out.

**Comment by QuentinBrosse** [comment]
The first time I try to run this query, en error tel me that I have to create an index: `The query requires an index. You can create it here <link>`. So I click on the link and create the index:

<img width="938" alt="screen shot 2018-01-26 at 13 46 25" src="https://user-images.githubusercontent.com/10938538/35440369-613250c2-029f-11e8-8909-b6ca9cc2005d.png">

I retry to run the same query, this time I don't have any errors, but the results are empty.

Thanks for the reply. :)

**Comment by prescottprue** [comment]
@QuentinBrosse [`v0.2.6`](https://github.com/prescottprue/redux-firestore/releases/tag/v0.2.6) includes the fix that @danleavitt0 provided. Let me know if it doesn't work as expected.

**Comment by QuentinBrosse** [comment]
Thanks a lot, it works like a charm ! :)

**Comment by GitHubGreg** [comment]
Is it possible this bug has crept back in? I have the exact same issue as @QuentinBrosse . My field names are different, but it is identical. I am using react-redux-firebase 2.2.6 and redux-firestore 0.7.0.

Thanks.

**Comment by prescottprue** [comment]
@GitHubGreg Are you sure that your indexes are set? If so can you open a new issue with a repro and your exact queries - feel free to reference this issue as well

**Comment by GitHubGreg** [comment]
The console doesn't offer me the link to create the index, so I tried manually creating it but it still fails to return the firestore collection. I created a new issue [here](https://github.com/prescottprue/redux-firestore/issues/215).

Thanks!

**Comment by mufaddalmw** [comment]
@GitHubGreg https://www.fullstackfirebase.com/cloud-firestore/indexes this may help you, I got stuck in same situation but solved it with above ref.

**Comment by GitHubGreg** [comment]
In case anyone lands here with a similar issue, see this thread in case it is the same issue for you: https://github.com/prescottprue/redux-firestore/issues/215

**Comment by GitHubGreg** [comment]
Thanks @mufaddalmw
