### ISSUE TITLE
Querying subcollections always warns "Listener does not exist"

### ISSUE THREAD

**Issue by Floriferous** [prescottprue/redux-firestore#51]
In one of our components we are querying a subcollection like this:

```js
    firestoreConnect((props) => {
      const { userId } = props;

      if (props.userId) {
        return [
          {
            collection: 'stripeCustomers',
            doc: userId,
            subcollections: [{ collection: 'sources' }],
            storeAs: 'stripeSources',
          },
          {
            collection: 'stripeCustomers',
            doc: userId,
            subcollections: [{ collection: 'charges' }],
            storeAs: 'stripeCharges',
          },
        ];
      }
      return [];
    })
```

When starting the app, this always shows 2 warnings:

`Listener does not exist for stripeCustomers/someUserId/sources`
`Listener does not exist for stripeCustomers/someUserId/charges`

I looked at the code that generates these 2 errors, but was unable to understand whether this is a correct or incorrect warning, as it seems like the listener is not registered initially, and then the detachListener function is run for some reason?

https://github.com/prescottprue/redux-firestore/blob/05159d1525480fa634bfb366b2cfa2d812bb7673/src/utils/query.js#L178

**Comment by prescottprue** [comment]
Removed in `v0.2.6`. Thanks for reporting :)
