### ISSUE TITLE
`firestore.update` throws an error

### ISSUE THREAD

**Issue by cazzer** [prescottprue/redux-firestore#64]
I think this is a bug or a documentation error. Current running `redux-firebase@0.2.7`.

The `firestore.update` example in the [README.md](https://github.com/prescottprue/redux-firestore/blame/master/README.md#L109) is throwing the following error for me:
```
TypeError: Cannot read property 'apply' of undefined
wrapInDispatch
node_modules/redux-firestore/es/utils/actions.js:47
  44 |   meta: meta,
  45 |   payload: (0, _isObject3.default)(requestingType) ? requestingType.payload : { args: args }
  46 | });
> 47 | var methodPromise = args && args.length ? ref[method].apply(ref, _toConsumableArray(args)) : ref[method]();
  48 | return methodPromise.then(function (val) {
  49 |   var makePayload = function makePayload(_ref2) {
  50 |     var payload = _ref2.payload;
```
It is unclear if there is another method I should be using for updating records.

**Comment by prescottprue** [comment]
The code is supposed to be:

```
props.store.firestore.update(`todos/${key}`, { done })
```

Notice how there were three arguments passed where there should have just be two. I'll make sure to fix that in the README.

Let me know if the new snippet doesn't work as you expect. Thanks for reporting!

**Comment by cazzer** [comment]
Thanks for the quick reply and documentation fix, it works as expected.
