### ISSUE TITLE
bug(reducer): subcollections ordered awkwardly in state

### ISSUE THREAD

**Issue by mechanical-turk** [prescottprue/redux-firestore#7]
suppose we have the following data schema:

root collection: todos
```
{
   title: String,
   completed: Boolean,
   todo_items: SubCollection
}
```

Therefore the path to todo_items of a collection with the ID: 6mjAkNg3XvB3v55LDIjy, will be: `todos/6mjAkNg3XvB3v55LDIjy/todo_items`.

When we have the following 2 `firestoreConnect()`s simultaneously, we are put in an awkward situation.

- `firestoreConnect(['/todos'])`
- `firestoreConnect(['/todos/6mjAkNg3XvB3v55LDIjy/todo_items'])`

In this situation, both of these connections try to store the collections under the same key: `todos`. Under `firestore.data`, they are conveniently nested. Therefore, a user can store subcollections of a document under the same key, without having to look for it somewhere else. This is actually really really cool.

The problem is under `firestore.ordered`. Once the subcollection is added, `firestore.ordered` loses the ordered list invariant. The data-structure becomes an array-object hybrid, and renders `firestore.ordered` unusable.

**Comment by prescottprue** [comment]
Great call, hadn't thought of that initially.

I like what you are saying for the fix. As for updating the ordered, maybe we look for the item in the array by key and update it?

**Comment by mechanical-turk** [comment]
where does the data for `store.ordered` come from? Do we process it anywhere?

For the time being, in order to avoid using `store.ordered`, I'm getting all my data from `store.data`, and sort them in the client. Client-side sorting is honestly not that big of a deal.

I created the following 2 library methods:

```js
export const objToArr = (data, sorterFn) => {
  const fixedData = data || {};
  const result = Object.keys(fixedData).map((curKey) => {
    const curElem = fixedData[curKey] || {};
    return {
      ...curElem,
      id: curKey,
    };
  });
  if (sorterFn) { result.sort(sorterFn) };
  return result;
}

export const generateSort = (sorterFn) => ({
  mapperFn,
  isDescending,
}) => (a, b) => {
  const coefficient = isDescending ? -1 : 1;
  const aMapped = mapperFn(a);
  const bMapped = mapperFn(b);
  const rawResult = sorterFn(aMapped, bMapped);
  return rawResult * coefficient;
}
```

I can put any collection into the `objToArr` function. If I want to, I can add a sorter function, which'll determine how the resulting array will be sorted. 

`generateSort` is a double-curried function. First, you'll need to put a normal sorting function in there. Once you do that, you get another function that takes in 2 params: A mapper function and a flag that determines whether we want ascending or descending order.

The duty of the mapper function is to map all the objects in the collection, into a value which we'll use to sort the array. For example, let's say we have the following collection:

```js
const data = {
  'nfewkjfnio23j40': { title: 'firstItem', completed: false },
  'jmfwnef203304': { title: 'secondItem', completed: false },
}
```

If we want to sort them alphanumerically, we can do the following:

```js
const alphaNumericSort = (a, b) => {
  const aLower = a.toLowerCase();
  const bLower = b.toLowerCase();
  if (aLower < bLower) return -1;
  if (aLower > bLower) return 1;
  return 0;
};

const generateAlphanumericSort = generateSort(alphaNumericSort);

objToArr(
  data,
  generateAlphanumericSort({
    mapperFn: (item) => item.title,
  })
)
```

If we want to have them sorted in descending order, we can further add the following:

```js
objToArr(
  data,
  generateAlphanumericSort({
    mapperFn: (item) => item.title,
    isDescending: true,
  })
)
```

Converting a collection into an array is quite a common task. I suggest that we do a more robust implementation of this scheme, so that we can sort any object into any kind of array in the client side.

**Comment by mechanical-turk** [comment]
This was not meant to be the only solution for the current problem, but a general solution for sorting collections.

A simpler solution for the time being might be storing the collections under different names. For example, all the todos can be stored under `store.ordered.todos`, whereas the todo_items can be stored under `store.ordered['todos/todo_items']`.

But that creates further problems, one being that we'd need to store objects and arrays mixed together.

The most elegant solution in my mind is the following: We could store the subcollection right under the document, just like we do in `store.data`, but instead of keeping it as a collection, we store an ordered array. So each todos list will have each of their todo items sorted within themselves.

This way, the data will be kept closest to the shape we'll use it in.

**Comment by prescottprue** [comment]
@mechanical-turk `state.firestore.ordered` comes from the results of the query the same way that data does [as you can see on this line here](https://github.com/prescottprue/redux-firestore/blob/master/src/actions/firestore.js#L133-L136).

The main issue being that if there is an update to a single item in a collection, we will want to find that item in the already ordered array, and update its value. That way the order of the collection is not changed by the single doc update, but all of the docs in ordered will be just as up to date as the ones in `data`.

**Comment by prescottprue** [comment]
[`v0.1.0-beta.5`](https://github.com/prescottprue/redux-firestore/commit/88d55dbc8c1c23a792621f57243a8140fbdd3695) includes changes that fix this.

Let me know if this doesn't work as expected. I'm sure there is still plenty more to come with respect to subcollection querying.
