### ISSUE TITLE
Deleting object properties doesn't update the UI since 0.3.1

### ISSUE THREAD

**Issue by will-hart** [prescottprue/redux-firestore#71]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

If you have an object within a document, then **deleting** keys from that object doesn't update the `firestore.data` variable, however  `firestore.ordered` is updated. This means the if the component uses `firestore.data` then the UI is not updated to reflect deleted keys. The database *is* correctly updated and refreshing the browser shows the expected values.

See https://codesandbox.io/s/m3jm3roko8 for an example.

In both `0.3.1` and `<0.3.1` I can add an item and have it appear in the UI. The Redux diff looks like this for `0.3.1`

![image](https://user-images.githubusercontent.com/391950/36847702-424bcc54-1db3-11e8-8c8e-0b1fc0bc1d27.png)

and like this for `0.2.8`

![image](https://user-images.githubusercontent.com/391950/36848190-a3aab43c-1db4-11e8-8490-e74c214f1e69.png)

However when deleting items, `0.3.1` has this diff:

![image](https://user-images.githubusercontent.com/391950/36847717-516e76b4-1db3-11e8-92cd-76ae89ff64e6.png)

and `0.2.8` has this diff

![image](https://user-images.githubusercontent.com/391950/36848230-c1223c56-1db4-11e8-8099-67f01a1ee3b6.png)

Note that `0.3.1` only deletes the `ordered` value, but leaves the `data` value intact while `0.2.8` correctly deletes its `data` value and doesn't set an `ordered` value.

**What is the expected behavior?**

Values in `firestore.data` are updated to reflect the database value when object properties are deleted. This occurs as expected prior to `0.3.1`.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

See code sandbox

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

https://codesandbox.io/s/m3jm3roko8  

Hit the add and delete buttons. Notice that items are added correctly, but not removed when they are deleted. Hit refresh and the deleted items will go away. 

It's a bit fiddly, but you can remove the `redux-firestore` dep and change it to `0.2.8` then refresh to try with the working version, although it sometimes takes a few tries to change the version.

The database looks like this if you want to create your own.

![image](https://user-images.githubusercontent.com/391950/36847397-3e31d074-1db2-11e8-8055-99493a819a11.png)

❤️

**Comment by prescottprue** [comment]
@will-hart It looks like we might have to add a case for `DELETE_SUCCESS` here the same way we did with the orderedReducer in #45. Using `assign` before made things work for this case, but it seemed to be part of what was causing #49 (hence the change to `merge`).

I was also planning on having an option of whether or not to merge [similar to the `mergeOrdered` option](https://github.com/prescottprue/redux-firestore#mergeordered) that was just added

**Comment by prescottprue** [comment]
@will-hart can you confirm that [the reverted code in this PR](https://github.com/prescottprue/redux-firestore/pull/72) fixes things for you? Want to make sure I am fully catching the use case.

**Comment by will-hart** [comment]
Awesome! I'll try to have a look over the weekend.

**Comment by prescottprue** [comment]
The v0.3.2 fix reverted the usage of `merge` which fixes this. Going to make sure to add a test case for this before trying to fix the merging of subcollections.

**Comment by amaldare93** [comment]
this issue is still happening for me,

im running these versions

```
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-firebase": "3.2.0",
    "react-redux": "^5.0.6",
    "react-redux-firebase": "^2.0.5",
    "redux": "^3.7.2",
    "redux-firestore": "^0.3.2",
    "redux-thunk": "^2.2.0",
```

I am deleting keys like this:
```
const batch = firestore().batch()
      const chatRef = firestore()
        .collection('chats')
        .doc(chatId)
      const currentUserChatsRef = firestore()
        .collection('user_chats')
        .doc(getCurrentUserId())
      const targetUserChatsRef = firestore()
        .collection('user_chats')
        .doc(targetUserId)

      batch.delete(chatRef)

      batch.update(currentUserChatsRef, {
        [targetUserId]: getFirebase().firestore.FieldValue.delete(),
      })

      batch.update(targetUserChatsRef, {
        [getCurrentUserId()]: getFirebase().firestore.FieldValue.delete(),
      })

      return batch.commit().catch(err => console.error(err))
```

and tracking them like this:
```
@firestoreConnect((props, { firebase }) => [
  {
    collection: 'user_chats',
    doc: firebase.auth().currentUser.uid,
  },
])
```

am i doing anything wrong? i see the things being deleted in the firebase console. but my app doesnt respond to those changes unless i kill and restart

**Comment by prescottprue** [comment]
@amaldare93 A few things:
* Calling update directly will call to update Firestore, but a listener will still be required on that path. Since it looks like you are only creating a listener for the current user, removing data from `targetUserChatsRef` **will not** update redux store (this is because an action needs to be dispatched for state to be updated, which will not happening when calling batch.update as you did)
* It is considered "bad practice" to use UID from firebase directly (since it is not passed as a prop, auth state changing will not re-render components)

**Comment by amaldare93** [comment]
1. thats fine for my use case, I only need to update based on current user, not target user (im probably going to refactor that out bc it feels dirty to write to another user's doc)

2. Thanks for the tip, what is the best way to access the current user id? should i pull it from firestore profile? 

and thanks for looking in to it :)

**Comment by lorenzosfarra** [comment]
Sorry to write on a closed ticket, but I think that somehow the problem persists in a different form.

Here's the involved versions

```
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.1.8",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.0",
    "redux-firestore": "^0.5.8",
```

In my component I have:

```
[...]

componentDidMount() {
        console.log(this.props);
        const {firestore} = this.props;
        firestore.get('tests');
        firestore.setListener({collection: 'tests'});
    }

componentWillUnmount() {
        const {firestore} = this.props;
        firestore.unsetListener({collection: 'tests'});
    }

render() {
        const { tests} = this.props;
        <div>
                    {
                        tests && tests.map(test => (
                            <div key={test.id}>
                                {JSON.stringify(test)}
                            </div>
                        ))
                    }
                </div>
}

[...]

export default compose(
    firebaseConnect(),
    firestoreConnect(),
    connect((state) => ({
        tests: state.firestore.ordered.tests
    }))
)(Dashboard);
```

And I am printing the value of `this.props.tests` without problems.
When I go to the Firebase console -> Firestore, I have the following use cases:

1. I add something to /tests --> the UI is updated correctly
2. I modify something into /tests --> the UI is updated correctly
3. I delete an entry from /tests --> the UI is NOT updated

The state is the opposite of the first message here: `data.tests` is updated, but `ordered.tests` is not.

I am quite new into the react world so there is a chance that I am not perfectly following the rules here, and anyway, if I can add some valuable detail, please just let me know.

Thanks in advance,
  Lorenzo

**Comment by JCBsystem** [comment]
for its the .data is not updated 

state.firestore.data = keep data after its deleted 
state.firestore.ordered =  updates data correct

"react-redux": "^5.0.7",
 "react-redux-firebase": "^2.2.5",

**Comment by prescottprue** [comment]
@lorenzosfarra I believe this is a duplicate of [this issue ](https://github.com/prescottprue/redux-firestore/issues/140) and a few others that are open. Try upgrading to the `v1.0.0-*` pre-releases by installing from the `alpha` tag [and checking out the new api](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) - it is much better suited to subcollections. Still going to try to address this in `0.*.*`, but trying to consolidate where I'm making updates about this issue
