### ISSUE TITLE
bug(query): Subcollections return an error

### ISSUE THREAD

**Issue by robertedjones** [prescottprue/redux-firestore#74]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Trying to get a subcollection produces the error: 

> Error: Collection can only be run on a document. Check that query config for subcollection: "details" contains a doc parameter.

**What is the expected behavior?**
The subcollection is retrieved

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
Current version, haven't used previous versions

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
Use the following code to reproduce. I have also tried adding a document parameter to subcollection object without success.

```javascript
componentWillMount() {
    
    const { firestore } = this.context.store;

    firestore.get({
      collection: 'users',
      document: 'bob',
      subcollections: [{ collection: 'details' }],
    });
}
```

**Comment by danleavitt0** [comment]
The get object should have `doc` not `document`

So: 
```js
firestore.get({
  collection: 'users',
  doc: 'bob',
  subcollections: [{collection: 'details'}]
})

**Comment by prescottprue** [comment]
@danleavitt0 Thanks for responding. @robertedjones if that does not fix your issue, please reach out.
