### ISSUE TITLE
firestore.add doesnt work

### ISSUE THREAD

**Issue by mechanical-turk** [prescottprue/redux-firestore#8]
the following code throws the following error
```
firestore.add('/todos', { title: 'todosTitle' });
```

-->

`FirebaseError: Function CollectionReference.doc() requires its first argument to be of type string, but it was: a custom Object object`

So I think somewhere in the middle where we take the params and pass it to the internal method, we're messing something up.

**Comment by prescottprue** [comment]
Yup, I am seeing this too, and I agree with your theory. Good find.

**Comment by prescottprue** [comment]
It seems it was affecting the other methods as well. Fixed in the v0.1.0-alpha release
