### ISSUE TITLE
Creating a document no longer seems to update the dataReducer

### ISSUE THREAD

**Issue by MettaProgrammer** [prescottprue/redux-firestore#84]
I updated from 0.3.2 to 0.4.1 for the on deletion fix for the dataReducer however it appears to no longer push the new document to the store. 

I can see that the document is successfully created in my firestore dashboard but I receive no new props, I do receive new props on document deletion and modification just not creation. 

If I switch to the orderedReducer then it works as expected, it's also working perfectly fine with 0.3.2 which I have now reverted to.

**Comment by prescottprue** [comment]
@MettaProgrammer Thanks for reporting. Will look into this today.
