### ISSUE TITLE
[bug] Limit is ignored when the rest of query meta are the same

### ISSUE THREAD

**Issue by ivawzh** [prescottprue/redux-firestore#90]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Context: 
  Firstly, set listener `{ collection: 'book', limit: 3}`
  Later, set listener `{ collection: 'book', limit: 6}`

Currently, the listener won't be updated. It remains to be `{ collection: 'book', limit: 3}`. It also does not trigger the second query at all.

That's because `limit` is ignored when constructing listener name, code: https://github.com/prescottprue/redux-firestore/blob/b394053ce528f7b6c5317860eff5e71a65fbc827/src/utils/query.js#L163

**What is the expected behavior?**
Expect it will trigger the second query. Either the listener will be updated to the most recent query  `{ collection: 'book', limit: 6}` or there will be two listeners.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
v0.4.3

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
As mentioned above.

**Comment by prescottprue** [comment]
Fixed as part of [`v0.5.0` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.5.0). Reach out if it doesn't work as expected.

Thanks for reporting!
