### ISSUE TITLE
complete example : yarn start : unknown plugin "lodash"

### ISSUE THREAD

**Issue by CoVoCre** [prescottprue/redux-firestore#95]
**Do you want to request a *feature* or report a *bug*?**  
BUG

**What is the current behavior?**
example complete fails to run/build

**What is the expected behavior?**
Run/build example complete

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
I have yarn 1.4.0, did not change any of the package.json, but got, when running `yarn` : 
```
Please choose a version of "react-redux-firebase" from this list: (Use arrow k
eys)
❯ 2.1.1 
  2.1.0 
  2.0.7-alpha 
  2.0.6 
  2.0.5 
  2.0.4 
  2.0.3 
```
I chose the latest 2.1.1
Then
````
warning codecov > request > node-uuid@1.4.8: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "firebase > @firebase/firestore@0.4.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/functions@0.1.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/database@0.2.2" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/storage@0.1.9" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/messaging@0.2.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/functions > @firebase/messaging-types@0.1.3" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/firestore > @firebase/firestore-types@0.3.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/database > @firebase/database-types@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/auth > @firebase/auth-types@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/storage > @firebase/storage-types@0.1.3" has unmet peer dependency "@firebase/app-types@0.x".
````
And then when running `yarn start` : 
<img width="560" alt="capture d ecran 2018-05-11 a 19 20 47" src="https://user-images.githubusercontent.com/25605953/39937590-8410559a-5550-11e8-8835-23ad38f93344.png">

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by CoVoCre** [comment]
I tried the fix proposed [there](https://github.com/gajus/react-css-modules/issues/31#issuecomment-160108211) but only got more problems...

**Comment by prescottprue** [comment]
@CoVoCre It seems to be because it is defaulting to the root `.babelrc` instead of using the babel settings in the ` webpack.config.js`. I will look into a way to prevent this from happening.

**Comment by prescottprue** [comment]
Just merged that `babelrc: false` change along with a few other small things.

Like I said, I wasn't able to repro, so not positive of if it will fix it on your system.

Let me know if things are still not working for you and we can reopen. Thanks for reporting!
