### ISSUE TITLE
bug(orderedReducer): deleting an item from nested collection doesn't remove item from ordered reducer

### ISSUE THREAD

**Issue by nickw** [prescottprue/redux-firestore#96]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

When calling `delete`:
```
this.props.firestore.delete(`feeds/${this.props.auth.uid}/questions/${this.state.currentQuestion.id}`);
```

I see the action being fired with the correct payload:
<img width="311" alt="screen shot 2018-05-12 at 2 03 55 pm" src="https://user-images.githubusercontent.com/3907/39961561-8fae7844-55ed-11e8-9381-48c9ef0f3904.png">

And I see the `data` reducer showing `null` for the deleted item(s), but the `ordered` reducer still contains the deleted item(s):
<img width="304" alt="screen shot 2018-05-12 at 2 03 06 pm" src="https://user-images.githubusercontent.com/3907/39961563-a5db61a4-55ed-11e8-8fdc-019492a0fe4d.png">

**What is the expected behavior?**

Calling delete should remove items from both the `data` and `ordered` reducers.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**

```
"react": "16.3.1",
"react-native": "0.55.3",
"react-native-firebase": "^4.0.4",
"react-redux": "^5.0.7",
"react-redux-firebase": "^2.1.1",
"redux": "^4.0.0",
"redux-firestore": "^0.5.1",
```

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**Comment by prescottprue** [comment]
@nickw Thanks for reporting. Out of curiosity, do you have a listener attached for that path?

**Comment by nickw** [comment]
@prescottprue Hmm I don't believe so. Here's the relevant pieces of code:

```javascript
class Game extends Component {
  componentDidMount() {
    this.handleLoadQuestions();
  }

  handleLoadQuestions = () => {
    this.props.firestore
      .get({
        collection: 'feeds',
        doc: this.props.auth.uid,
        subcollections: [
          {
            collection: 'questions',
            orderBy: [['index']],
            limit: QUESTIONS_PER_DECK,
          },
        ],
      })
      .then(querySnapshot => {
        this.setState({
          currentQuestion: this.props.feeds[0].questions[
            this.state.currentQuestionIndex
          ],
        });
      });
  };

  handleAnswerQuestion = () => {
    this.props.firestore.delete(
      `feeds/${this.props.auth.uid}/questions/${this.state.currentQuestion.id}`
    );
  };

  render() {
    const { feeds } = this.props;

    // This should decrement but doesn't:
    console.log('questions.length', get(feeds[0], 'questions.length'));

    return (
      <QuestionCard
        question={this.state.currentQuestion}
        currentAnswer={this.state.currentAnswer}
        onAnswerQuestion={this.handleAnswerQuestion}
        onNextQuestion={this.handleNextQuestion}
      />
    );
  }
}

const mapStateToProps = ({ firestore, firebase }) => ({
  feeds: get(firestore, 'ordered.feeds', []),
  auth: firebase.auth,
  profile: firebase.profile,
});

export default compose(withNavigation, withFirestore, connect(mapStateToProps))(
  Game
);

```

**Comment by prescottprue** [comment]
Fixed in [`v0.5.2` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.5.2) with included unit tests. Thanks for reporting!

**Comment by nickw** [comment]
Fixed confirmed - thanks @prescottprue !

**Comment by prescottprue** [comment]
Glad to hear @nickw. You may have already noticed, but `react-redux-firebase` has the `firestoreConnect` HOC which manages listeners on component mount/unmount for you so you don't have to call to get data on component mount.

**Comment by nickw** [comment]
Ok thanks, I'll give it a shot! Does that also inject a `firestore` prop or do I also need `withFirestore`?

**Comment by prescottprue** [comment]
@nickw Yup, it also injects the `firestore` prop 😄
