### ISSUE TITLE
bug(query): queries made with firebase v5 SDK not writing to state

### ISSUE THREAD

**Issue by igor-lemon** [prescottprue/redux-firestore#98]
I can't to subscribe on collection
![image](https://user-images.githubusercontent.com/14764799/40026108-b35a42dc-57dc-11e8-8b6d-b41214165fb5.png)

I tried do 
`firestore.onSnapshot({ collection: 'sources', doc: profile.uid })`
`firestore.onSnapshot({ collection: `'sources.${profile.uid}'`})`

I tried to change to setListener insted onSnapshot. Any results...

**Comment by prescottprue** [comment]
@igor-lemon Not sure what you mean by "Any results". What does your `connect` logic look like (i.e. how you are connecting to state). Remember that creating this listener will only get the data into redux state, you are still need to get that redux state into your component.

The second example you provided is not valid since it uses dot notation, but your first example should work fine.

**Comment by igor-lemon** [comment]
@prescottprue Thanks for fast answer.
I understand it. I mean that I have inited listeners but I didn't have any data. I posted an screenshot with my real structure of DB. It's my Redux store.
![image](https://user-images.githubusercontent.com/14764799/40028541-02799f88-57e8-11e8-923c-cfc8befffabd.png)

Very interesting. It works well if I have not deep doc's.
![image](https://user-images.githubusercontent.com/14764799/40028660-d2f82008-57e8-11e8-8c75-5b51a6b8b73f.png)

Let's try to make deep doc and set listeners.

**Comment by prescottprue** [comment]
@igor-lemon What you are seeing is expected. You are showing that you are creating a listener for a document. That will not include data within that document's subcollections, for that you need a different listener config:

```js
firestore.onSnapshot({ collection: 'sources', doc: profile.uid, subcollections: [{ collection: 'cards' }] })
```

If you want both the document and the subcollection you will have to create a listener for each separately:

```js
firestore.onSnapshot({ collection: 'sources', doc: profile.uid })
firestore.onSnapshot({ collection: 'sources', doc: profile.uid, subcollections: [{ collection: 'cards' }] })
```

#52 includes discussion about a feature to be able to query both a document and that document's subcollection within one query, but that is not yet a feature (originally intended as this can cause major performance implications with large collections).

Keep in mind that you will have to remove these listeners (as you would with the Firebase JS SDK directly). You can use `firestoreConnect` from `react-redux-firebase` to manage these listeners for you automatically on mount/unmount of your component.

**Comment by igor-lemon** [comment]
I tried it too :) Before write issue I recombined dozens of ways

```
firestore.onSnapshot({ collection: 'sources', doc: profile.uid }) // ===> Is null
firestore.onSnapshot({
  collection: 'sources',
  doc: profile.uid,
  subcollections: [{ collection: 'cards' }]
}) // ===> Is null
```
```
// string notation:
firestore.onSnapshot(`sources/${profile.uid}`) // ===> Is null
firestore.onSnapshot(`sources/${profile.uid}/cards`) // ===> Is null
```

**Comment by prescottprue** [comment]
@igor-lemon It is pretty hard to debug any further with the currently provided info. The provided syntax works for a large number of applications, so it seems like it may have to do with your setup.

Do you have rules on your Firestore instance? Where are you getting the Firestore instance from? How are you calling `firestore.onSnapshot`, are you sure it is the dispatch decorated version (i.e. from store)? Is it within a component?

**Comment by igor-lemon** [comment]
So, you closed the ticket early. Simple try to listen collection. 
`firestore.onSnapshot({ collection: 'sources' })`

I have similar error
https://github.com/prescottprue/redux-firestore/issues/99

**Comment by prescottprue** [comment]
@igor-lemon I was unaware of the fact that you were using firebase v5 or that there were error logs of any kind.  There were some breaking changes in the v5 update, so switching back to v4.*.* should work for now.

To make sure your issue can be correctly reproduced in the future, it will help to provide the Firebase library version as well as any console errors you may be seeing.

I have already started work on handling v5 syntax due to #99, but I will reopen this for now to make sure it is tested as well.

**Comment by prescottprue** [comment]
The [`v0.5.3` release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.5.3) fixes this, and the examples were updated to use firebase `^5.0.2`. Thanks for reporting!

**Comment by igor-lemon** [comment]
Thank you so much! Great lib! :)
