### ISSUE TITLE
"QuerySnapshot.docChanges has been changed from a property into a method" error.

### ISSUE THREAD

**Issue by PAK90** [prescottprue/redux-firestore#99]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Collection doesn't load, get an error in console.

**What is the expected behavior?**
Collection in my Firestore should be loaded.

**Which versions of dependencies, and which browser are affected by this issue? Did this work in previous versions or setups?**
I'm using latest (0.5.2) version in latest Chrome.

**Steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Very simple so far:

```
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux'
import { compose } from 'recompose';
import { firestoreConnect } from 'react-redux-firebase'

function Main(props) {
  console.log(props);
  return (
    <div>Cards go here</div>
  )
}

Main.propTypes = {};

const enhance = compose(
  firestoreConnect(['cards']),
  connect((state) => ({
    cards: state.firestore.ordered.cards,
  }))
);

export default enhance(Main);
```
`Cards` is undefined and I get the following error in console: 
```
Uncaught Error: QuerySnapshot.docChanges has been changed from a property into a method, so usages like "querySnapshot.docChanges" should become "querySnapshot.docChanges()"
    at new FirestoreError (index.cjs.js:346)
    at throwDocChangesMethodError (index.cjs.js:17164)
    at Function.get (index.cjs.js:17176)
    at Object.next (firestore.js:164)
    at next (index.cjs.js:16990)
    at index.cjs.js:15021
```

I have a top-level `cards` collection in my Firestore which has a few items in it, shouldn't be returning undefined. I'm guessing it's due to this error.

**Comment by prescottprue** [comment]
Thanks for reporting! Which version of the Firebase JS SDK are you using? Thinking that there was a recent change causing this.

I'll work on a fix, but I'm also going to look into modifying the tests to check for both older and newer versions of the Firebase SDK (I think they currently use v4 instead of v5).

**Comment by PAK90** [comment]
You mean the [firebase npm package](https://www.npmjs.com/package/firebase), I'm assuming? I'm using v5.0.2 of that.

**Comment by LetsSupport** [comment]
Experiencing the same error. Using firebase v5.0.4

**Comment by nikinfinity2** [comment]
I am developing ionic app 3 using angularfire2 "angularfire2": "5.0.0-rc.6" and i am getting the same error. Please provide some solutions to fix this issue.

**Comment by prescottprue** [comment]
@nikinfinity2 Are you using redux-firestore with angularfire?

**Comment by nikinfinity2** [comment]
no redux-firestore .... i am using angularfire2's firestore like below.
angularfire2/firestore

**Comment by nikinfinity2** [comment]
i dont know about redux-firestore... can i use it with ionic 3

**Comment by prescottprue** [comment]
@nikinfinity2 This is the repo for redux-firestore, so if you are not using, your issue is posted in the incorrect place.

Usage with ionic 3 is possible, but not sure I understand why it would be mixed with angularfire2?
